//! The algorithm2e model (`packages::VENDORED_PATCHES`: the real
//! `algorithm2e.sty` through the expansion engine, its box layer re-modelled
//! by `flashtex-algorithm2e.sty`) and algorithmic.sty's label column
//! (`flashtex-algorithmic.sty`) against pdfLaTeX.
//!
//! `tests/oracle/algorithm2e/expected.json` is generated by `generate.py`
//! there (oracle only; Cargo never runs TeX): per probe, the
//! whitespace-normalised `pdftotext` text of what pdfTeX set -- every
//! keyword, line number, input/output label, comment and caption. The
//! compiler must set the same characters (as a multiset: its own layout
//! orders a side comment differently from pdftotext) and report no error.

use std::collections::BTreeMap;
use std::path::Path;

use flashtex_compiler::diagnostics::Severity;
use flashtex_compiler::incremental::{compile_full, LayoutConstraints};
use flashtex_compiler::json::{self, Value};
use flashtex_compiler::parser::{parse, Block};

/// The non-blank characters of `text`, counted. A no-break space is a
/// blank; the compiler's rule stand-in (`─`, its runtime-v1 layout has no
/// rule item) is no character pdfTeX sets.
fn characters(text: &str) -> BTreeMap<char, usize> {
    let mut counts = BTreeMap::new();
    for c in text.chars() {
        if c.is_whitespace() || c == '\u{a0}' || c == '─' {
            continue;
        }
        *counts.entry(c).or_insert(0) += 1;
    }
    counts
}

fn compiled_text(source: &str) -> (String, Vec<String>) {
    let result = compile_full(source, LayoutConstraints::default());
    let errors: Vec<String> = result
        .diagnostics
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .map(|d| d.message.clone())
        .collect();
    let text = result
        .pages
        .iter()
        .flat_map(|page| page.items.iter().map(|item| item.text.clone()))
        .collect::<Vec<_>>()
        .join(" ");
    (text, errors)
}

#[test]
fn every_probe_sets_the_characters_pdflatex_sets() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/oracle/algorithm2e");
    let text = std::fs::read_to_string(dir.join("expected.json")).unwrap();
    let root = json::parse(&text).expect("expected.json parses");
    let Some(Value::Obj(probes)) = root.get("probes") else { panic!("probes") };
    assert!(!probes.is_empty());
    for (name, probe) in probes {
        let source = std::fs::read_to_string(dir.join("probes").join(name)).unwrap();
        let expected = probe.get("text").and_then(Value::as_str).expect("text");
        let (compiled, errors) = compiled_text(&source);
        assert!(errors.is_empty(), "{name}: {errors:?}");
        let (want, got) = (characters(expected), characters(&compiled));
        let mut differences = Vec::new();
        for (c, n) in &want {
            let m = got.get(c).copied().unwrap_or(0);
            if m != *n {
                differences.push(format!("{c:?}: pdflatex {n}, compiler {m}"));
            }
        }
        for (c, m) in &got {
            if !want.contains_key(c) {
                differences.push(format!("{c:?}: pdflatex 0, compiler {m}"));
            }
        }
        assert!(differences.is_empty(), "{name}: {differences:?}\npdflatex: {expected}\ncompiler: {compiled}");
    }
}

/// algorithmic.sty's `\ALC@item` places every line's number `\ALC@tlm`
/// before the line's text: `\labelsep` in the outermost list, plus the
/// `\leftmargin` of every enclosing `ALC@g` block, so a nested line's
/// number ends in the outermost column. The model
/// (`flashtex-algorithmic.sty`) sets each item's label gap to exactly that.
#[test]
fn algorithmic_nested_lines_hang_their_numbers_in_the_outermost_column() {
    let source = "\\documentclass{article}\\usepackage{algorithmic}\\begin{document}\
        \\begin{algorithmic}[1]\\STATE $y \\gets 1$\\IF{$n > 0$}\\STATE $y \\gets x$\
        \\FOR{$i = 1$ to $n$}\\STATE $y \\gets y x$\\ENDFOR\\ENDIF\\end{algorithmic}\\end{document}";
    let parsed = parse(source);
    let errors: Vec<_> = parsed.diagnostics.iter().filter(|d| d.severity == Severity::Error).collect();
    assert!(errors.is_empty(), "{errors:?}");
    // (nesting depth, label gap) of every numbered line.
    let mut gaps = Vec::new();
    for block in &parsed.blocks {
        if let Block::ListItem { label: Some(_), labelsep_pt, lists, .. } = block {
            gaps.push((lists.len(), labelsep_pt.expect("the model sets every gap")));
        }
    }
    assert_eq!(gaps.len(), 7, "{gaps:?}");
    let outer = gaps.iter().find(|(depth, _)| *depth == 1).map(|(_, gap)| *gap).expect("an outer line");
    for (depth, gap) in &gaps {
        // \ALC@tlm = \labelsep (0.5em) + (depth - 1) * \algorithmicindent (1em).
        let expected = outer * (1.0 + 2.0 * (*depth as f64 - 1.0));
        assert!((gap - expected).abs() < 0.05, "depth {depth}: gap {gap}, expected {expected} ({gaps:?})");
    }
    assert!(gaps.iter().any(|(depth, _)| *depth == 3), "{gaps:?}");
}
