//! `\caption`'s float type (latex.ltx `\@captype`) against pdfLaTeX.
//!
//! `tests/oracle/captype/expected.json` is generated by `generate.py` there
//! (oracle only; Cargo never runs TeX): for each probe under `probes/`, the
//! caption labels pdfTeX set in reading order -- `Figure 1:`, `Program 2:`
//! (the class's `\@makecaption` colon), `Algorithm 1`, `Recipe 1.1` (float.sty's
//! `ruled` style, `\floatc@ruled`, sets no colon). The compiler must set the
//! same label text for the same `\caption`s and report no error: the float
//! type is the innermost enclosing float, inherited through `center`,
//! `minipage` and every other nested environment, and float.sty's
//! `\newfloat`/`\floatname`/`\floatstyle`, algorithm.sty's `algorithm` and
//! wrapfig's `wrapfigure`/`wraptable` all set it.

use std::path::Path;

use flashtex_compiler::diagnostics::Severity;
use flashtex_compiler::incremental::{compile_full, LayoutConstraints};
use flashtex_compiler::json::{self, Value};

/// The compiler's caption label items (`Figure 1:`, `Algorithm 2`), in
/// document order, and its error diagnostics.
fn caption_labels(source: &str) -> (Vec<String>, Vec<String>) {
    let result = compile_full(source, LayoutConstraints::default());
    let errors: Vec<String> = result
        .diagnostics
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .map(|d| d.message.clone())
        .collect();
    let labels = result
        .pages
        .iter()
        .flat_map(|page| page.items.iter().map(|item| item.text.trim().to_string()))
        .filter(|text| {
            let mut words = text.split(' ');
            let label = words.next().unwrap_or("");
            let number = words.next().unwrap_or("");
            words.next().is_none()
                && matches!(label, "Figure" | "Table" | "Algorithm" | "Program" | "Recipe")
                && number
                    .trim_end_matches(':')
                    .split('.')
                    .all(|part| !part.is_empty() && part.chars().all(|c| c.is_ascii_digit()))
        })
        .collect();
    (labels, errors)
}

#[test]
fn caption_labels_match_pdflatex_for_every_probe() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/oracle/captype");
    let text = std::fs::read_to_string(dir.join("expected.json")).unwrap();
    let root = json::parse(&text).expect("expected.json parses");
    let Some(Value::Obj(probes)) = root.get("probes") else { panic!("probes") };
    assert!(!probes.is_empty());
    for (name, probe) in probes {
        let source = std::fs::read_to_string(dir.join("probes").join(name)).unwrap();
        let expected: Vec<&str> = probe
            .get("caption_labels")
            .and_then(Value::as_arr)
            .expect("caption_labels")
            .iter()
            .map(|v| v.as_str().expect("label"))
            .collect();
        let (labels, errors) = caption_labels(&source);
        assert!(errors.is_empty(), "{name}: errors {errors:?}");
        assert_eq!(labels, expected, "{name}: caption labels");
    }
}

#[test]
fn caption_outside_every_float_is_an_error_and_keeps_the_text() {
    let result = compile_full(r"Text \caption{Lost} more.", LayoutConstraints::default());
    assert!(result.diagnostics.iter().any(|d| {
        d.severity == Severity::Error && d.message.starts_with("\\caption outside float")
    }));
    assert!(result.pages[0].items.iter().any(|item| item.text.contains("Lost")));
}

#[test]
fn caption_inherits_the_float_through_nested_environments() {
    // `\@captype` is set in the float's group: a `center` or `minipage`
    // inside it sees the same type (pdflatex: `Program 2: Nested in center`).
    let (labels, errors) = caption_labels(
        r"\usepackage{float}\newfloat{program}{htbp}{lop}\floatname{program}{Program}\begin{program}\begin{center}\begin{minipage}{2in}x\caption{Deep}\end{minipage}\end{center}\end{program}",
    );
    assert!(errors.is_empty(), "{errors:?}");
    assert_eq!(labels, ["Program 1:"]);
}

#[test]
fn starred_caption_sets_no_label_and_steps_no_counter() {
    // caption.sty `\caption*`.
    let (labels, errors) = caption_labels(
        r"\usepackage{caption}\usepackage{algorithm}\begin{algorithm}\caption*{Unnumbered}\end{algorithm}\begin{algorithm}\caption{Numbered}\end{algorithm}",
    );
    assert!(errors.is_empty(), "{errors:?}");
    assert_eq!(labels, ["Algorithm 1"]);
}

#[test]
fn algorithm_package_options_select_the_float_style() {
    // algorithm.sty `plain`: `\floatc@plain`, the kernel's colon.
    let (labels, errors) =
        caption_labels(r"\usepackage[plain]{algorithm}\begin{algorithm}\caption{Euclid}\end{algorithm}");
    assert!(errors.is_empty(), "{errors:?}");
    assert_eq!(labels, ["Algorithm 1:"]);
}

#[test]
fn short_caption_argument_is_consumed() {
    let result = compile_full(
        r"\usepackage{algorithm}\begin{algorithm}\caption[Short]{Long text}\end{algorithm}",
        LayoutConstraints::default(),
    );
    let texts: Vec<&str> =
        result.pages.iter().flat_map(|p| p.items.iter().map(|i| i.text.as_str())).collect();
    assert!(!texts.iter().any(|t| t.contains("Short")), "{texts:?}");
    assert!(texts.iter().any(|t| t.contains("Long")), "{texts:?}");
}
