#set page(paper: "a4")
#set text(size: 11pt)
#text(fill: rgb("#1f6feb"))[glyph jumps colour quick brown fox origin quick lazy quick brown space space brown dog brown space quick fox dog quick colour quick dog quick jumps parity space jumps fox parity over fox lazy origin fox brown quick lazy page space glyph pixel pixel origin parity dog over dog brown parity page glyph pixel parity brown fox space over glyph jumps page space quick brown glyph glyph origin page pixel brown brown typesetting page brown quick parity pixel parity colour origin the pixel origin over fox page quick lazy parity jumps dog colour colour page brown over pixel colour typesetting jumps space typesetting space origin colour dog jumps brown over jumps dog dog the page over typesetting parity the jumps]

#text(fill: rgb("#d1242f"))[space origin glyph jumps quick pixel colour colour colour colour fox page colour quick lazy brown lazy pixel over fox glyph quick fox the jumps fox origin the brown lazy colour jumps typesetting origin origin page fox fox page pixel page page parity brown jumps fox glyph typesetting page over the lazy origin jumps the parity brown typesetting origin over origin dog glyph dog lazy dog colour dog lazy page origin the the typesetting page typesetting lazy origin pixel origin origin brown dog fox dog page lazy glyph lazy page the page origin brown fox colour lazy page over space glyph brown colour pixel colour brown over over jumps the jumps pixel jumps page origin jumps jumps the the fox]

#text(fill: luma(40%))[jumps space lazy lazy the typesetting lazy parity dog glyph typesetting space jumps quick origin pixel space jumps jumps the pixel over the jumps over jumps page fox quick glyph page fox quick dog lazy typesetting quick fox pixel the brown pixel glyph lazy typesetting pixel page dog typesetting lazy pixel jumps space fox colour pixel glyph brown dog space brown lazy parity fox jumps origin jumps typesetting jumps pixel dog fox colour page over dog over space colour glyph space lazy origin glyph brown origin the glyph pixel pixel the colour glyph parity brown fox dog fox brown typesetting typesetting quick over typesetting jumps space typesetting colour jumps page glyph brown typesetting quick over space brown typesetting the brown]

#text(fill: cmyk(80%, 10%, 0%, 20%))[typesetting brown dog brown typesetting fox pixel the glyph space typesetting jumps quick dog fox over typesetting quick over lazy parity parity lazy parity pixel over typesetting origin the typesetting quick the the lazy page dog pixel fox space page colour parity lazy dog glyph lazy jumps colour origin quick jumps the brown typesetting space over quick brown colour parity dog parity quick pixel over over typesetting pixel the typesetting origin glyph glyph dog quick parity lazy origin over the glyph colour brown page typesetting lazy dog the brown typesetting brown jumps colour quick colour the parity parity dog brown jumps colour glyph page jumps parity jumps quick space jumps the dog brown the quick jumps origin fox colour pixel]

#text(fill: rgb("#2da44e"))[quick the dog page typesetting the pixel brown brown brown page typesetting brown typesetting dog lazy dog pixel page colour brown page parity quick lazy brown jumps glyph typesetting parity jumps the page quick page typesetting fox lazy page parity parity pixel pixel pixel fox lazy parity brown page the parity pixel brown pixel typesetting colour lazy lazy brown brown jumps typesetting origin jumps typesetting fox origin dog page page colour the over the page pixel colour parity jumps space origin colour glyph fox glyph the glyph glyph colour fox lazy the parity typesetting origin brown colour colour brown origin space typesetting quick typesetting fox quick parity jumps dog typesetting space glyph lazy origin space the colour lazy brown quick]

#text(fill: oklab(60%, 0.1, -0.1))[space pixel jumps parity page quick jumps over page space glyph parity parity typesetting typesetting colour dog parity page colour fox over over brown lazy page dog pixel glyph pixel space jumps lazy dog brown over glyph brown glyph dog origin typesetting lazy the space colour space lazy colour typesetting glyph quick page typesetting origin jumps lazy brown typesetting dog colour colour pixel space parity the jumps quick space page page the brown colour pixel pixel dog fox dog jumps jumps fox pixel brown quick the jumps dog quick parity jumps typesetting space fox fox brown parity lazy colour typesetting dog the the parity pixel typesetting glyph dog page dog dog the space parity quick the lazy page space brown]

