#!/usr/bin/env python3
"""Regenerates `crates/compiler/src/color_names.rs` from the TeX Live sources.

    python3 crates/compiler/scripts/color_names.py [--texbin /Library/TeX/texbin]

Reads `dvipsnam.def` (graphics bundle), `svgnam.def` and `x11nam.def` (xcolor
bundle) through kpsewhich and keeps every colour specification exactly as
written in the file; `flashtex_compiler::color` normalises them the way
`\\definecolor` does. Oracle/build tooling only.
"""
import argparse, os, re, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "color_names.rs")


def provides(text):
    m = re.search(r"\\ProvidesFile\{([^}]*)\}\s*\[([^\]]*)\]", text)
    return f"{m.group(1)} {m.group(2).strip()}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--texbin", default="/Library/TeX/texbin")
    args = ap.parse_args()

    def read(name):
        path = subprocess.run([os.path.join(args.texbin, "kpsewhich"), name], capture_output=True,
                              text=True).stdout.strip()
        return open(path, encoding="latin-1").read()

    dvips = read("dvipsnam.def")
    dvips_rows = re.findall(r"\\DefineNamedColor\{named\}\{(\w+)\}\s*\{cmyk\}\{([^}]*)\}", dvips)
    sets = {}
    for key, file in (("SVG", "svgnam.def"), ("X11", "x11nam.def")):
        text = read(file)
        body = text.split(r"\preparecolorset{rgb}{}{}{%", 1)[1].split("}", 1)[0]
        rows = []
        for entry in body.replace("%", "").split(";"):
            entry = entry.strip()
            if entry:
                name, spec = entry.split(",", 1)
                rows.append((name, spec))
        sets[key] = (provides(text), rows)

    out = ["//! Named colour sets, generated by `scripts/color_names.py`; do not edit.",
           "//!",
           f"//! - `DVIPS`: {provides(dvips)} (`\\DefineNamedColor{{named}}{{..}}{{cmyk}}`),",
           "//!   loaded by xcolor's `dvipsnames` option (and color.sty's).",
           f"//! - `SVG`: {sets['SVG'][0]} (`\\preparecolorset{{rgb}}`), xcolor `svgnames`.",
           f"//! - `X11`: {sets['X11'][0]} (`\\preparecolorset{{rgb}}`), xcolor `x11names`.",
           "//!",
           "//! Specifications are kept verbatim; `color::normalize` applies",
           "//! xcolor's `\\XC@calc@...:N` normalisation when a colour is defined.",
           "",
           "/// dvipsnam.def: `(name, cmyk specification)`.",
           "pub(crate) const DVIPS: &[(&str, &str)] = &["]
    out += [f'    ("{n}", "{s}"),' for n, s in dvips_rows]
    out.append("];")
    for key in ("SVG", "X11"):
        out += ["", f"/// {sets[key][0].split()[0]}: `(name, rgb specification)`.",
                f"pub(crate) const {key}: &[(&str, &str)] = &["]
        out += [f'    ("{n}", "{s}"),' for n, s in sets[key][1]]
        out.append("];")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {len(dvips_rows)} dvips, {len(sets['SVG'][1])} svg, {len(sets['X11'][1])} x11 names")


if __name__ == "__main__":
    main()
