//! pdflatex oracle for `\emergencystretch` and the final line-breaking pass
//! (`tests/oracle/emergency/`, regenerated by its `generate.py`; no TeX runs
//! here). Every fixture is a paragraph under `\sloppy` or explicit
//! `\emergencystretch`/`\tolerance` at a narrow `\hsize`, with and without
//! microtype. Against pdfTeX 1.40.27's `\showbox` and log this checks the
//! pass that produced the breaks, the line breaks, each line's glue set ratio
//! (hpack's, over the real glue: emergency stretch only enters the badness of
//! the final pass), glyph x positions, and the sequence of Underfull/Overfull
//! `\hbox` warnings with TeX's `\hbadness`/`\hfuzz`. Paragraphs without
//! microtype are broken by both `layout_paragraph` and
//! `layout_paragraph_microtype`.

// Clippy debt in frozen old-engine code (D13): allowed, not refactored.
#![allow(clippy::collapsible_if, clippy::needless_late_init, clippy::while_immutable_condition, reason = "frozen old engine (D13): fixes only; clippy debt is allowed rather than refactored")]

mod mt_convert;

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use flashtex_paragraph_layout::{
    Algorithm, BreakMode, DiagnosticKind, FORCED_BREAK, Item, LineBreakParams, Lines, MicroItem, MicroLine,
    Microtype, layout_paragraph, layout_paragraph_microtype,
};
use mt_convert::*;

struct Case {
    items: Vec<Item>,
    micro: Vec<MicroItem>,
    params: LineBreakParams,
    protrude: i32,
    adjust: i32,
}

fn load(path: &Path) -> (Fixture, Case) {
    let name = path.file_stem().unwrap().to_string_lossy().to_string();
    let fx = load_fixture(&name, &fs::read_to_string(path).unwrap());
    let case = {
        let env = Env::from_fixture(&fx);
        let mut list = strip_list2(fx.list2.clone());
        if !matches!(list.last(), Some(Node::Glue(g)) if g.name.as_deref() == Some("parfillskip")) {
            list = finish_list1(list, &env);
        }
        let explicit_ctx = disc_contexts(&fx.list1);
        let explicit: Vec<bool> = disc_contexts(&list).iter().map(|c| explicit_ctx.contains(c)).collect();
        let mut conv = Conv { fonts: &fx.fonts, params: BTreeMap::new(), ids: BTreeMap::new() };
        let (mut items, mut micro) = conv.items(&list, &explicit, fx.int("hyphenpenalty"), fx.int("exhyphenpenalty"));
        items.push(Item::penalty(FORCED_BREAK));
        micro.push(MicroItem::default());
        let params = LineBreakParams {
            line_width: pt(env.hsize),
            mode: BreakMode::Justified,
            algorithm: Algorithm::TotalFit,
            pretolerance: f64::from(env.pretolerance),
            tolerance: f64::from(env.tolerance),
            emergency_stretch: pt(env.emergency_stretch),
            line_penalty: f64::from(env.line_penalty),
            adj_demerits: f64::from(env.adj_demerits),
            double_hyphen_demerits: f64::from(env.double_hyphen_demerits),
            final_hyphen_demerits: f64::from(env.final_hyphen_demerits),
            parindent: 0.0,
            left_skip: glue(&env.left_skip),
            right_skip: glue(&env.right_skip),
            baselineskip: 12.0,
            lineskip: 1.0,
            lineskiplimit: 0.0,
            hfuzz: pt(fx.int("hfuzz")),
            hbadness: f64::from(fx.int("hbadness")),
        };
        Case { items, micro, params, protrude: env.protrude_chars, adjust: env.adjust_spacing }
    };
    (fx, case)
}

/// Compares one breaker's result with pdfTeX; returns (failures, max glyph dx in pt).
fn compare(fx: &Fixture, lines: &Lines, mlines: Option<&[MicroLine]>, warn: &str, dx_limit: f64) -> (Vec<String>, f64) {
    let env = Env::from_fixture(fx);
    let mut fails = Vec::new();
    let want_pass = if warn.lines().any(|l| l == "pass emergency") {
        3
    } else if warn.lines().any(|l| l == "pass second") {
        2
    } else {
        1
    };
    if lines.stats.pass != want_pass {
        fails.push(format!("pass {} want {want_pass}", lines.stats.pass));
    }
    let expected: Vec<&Node> = fx.result.iter().filter(|n| matches!(n, Node::HBox { .. })).collect();
    if lines.lines.len() != expected.len() {
        fails.push(format!("{} lines, want {}", lines.lines.len(), expected.len()));
    }
    let mut max_dx = 0f64;
    for (k, (line, exp)) in lines.lines.iter().zip(&expected).enumerate() {
        let Node::HBox { children, sign, set, order, .. } = exp else { unreachable!() };
        let got: Vec<(u8, f64)> = line
            .runs
            .iter()
            .enumerate()
            .flat_map(|(ri, r)| {
                let has_chars = mlines.map_or(!r.glyphs.is_empty(), |m| !m[k].expansion[ri].is_empty());
                r.glyphs.iter().filter(move |_| has_chars).map(move |g| (g.gid as u8, (r.x + g.x_offset) * 65536.0))
            })
            .collect();
        let want_x = glyph_positions(&env, children, *sign, *order, *set);
        let codes = |v: &[(u8, f64)]| v.iter().map(|c| char::from(c.0)).collect::<String>();
        if codes(&got) != codes(&want_x) {
            fails.push(format!("line {k}: got {:?} want {:?}", codes(&got), codes(&want_x)));
            continue;
        }
        for (g, w) in got.iter().zip(&want_x) {
            max_dx = max_dx.max((g.1 - w.1).abs() / 65536.0);
        }
        // Glue set ratio as `\showbox` prints it (5 decimals; overfull = 1.0).
        let want_ratio = match sign {
            GlueSign::Normal => 0.0,
            GlueSign::Stretching => *set,
            GlueSign::Shrinking => -*set,
        };
        let got_ratio = line.ratio.max(-1.0);
        if *order == Order::Normal && (got_ratio - want_ratio).abs() > 2e-5 * want_ratio.abs().max(1.0) {
            fails.push(format!("line {k}: glue set {got_ratio:.6} want {want_ratio:.6}"));
        }
    }
    if max_dx > dx_limit {
        fails.push(format!("max glyph dx {max_dx:.5}pt"));
    }
    let want_warn: Vec<&str> = warn.lines().filter(|l| !l.starts_with("pass ")).collect();
    let got_warn: Vec<String> = lines
        .diagnostics
        .iter()
        .map(|d| match d.kind {
            DiagnosticKind::Underfull { badness } => format!("underfull {badness}"),
            DiagnosticKind::Overfull { excess } => format!("overfull {excess:.5}"),
        })
        .collect();
    let same = got_warn.len() == want_warn.len()
        && got_warn.iter().zip(&want_warn).all(|(g, w)| {
            match (g.strip_prefix("overfull "), w.strip_prefix("overfull ")) {
                (Some(a), Some(b)) => (a.parse::<f64>().unwrap() - b.parse::<f64>().unwrap()).abs() <= 1e-4,
                _ => g == w,
            }
        });
    if !same {
        fails.push(format!("warnings {got_warn:?} want {want_warn:?}"));
    }
    (fails, max_dx)
}

#[test]
fn emergency_pass_breaks_glue_and_warnings_match_pdftex() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/oracle/emergency/expected");
    let mut paths: Vec<_> = fs::read_dir(&dir)
        .expect("emergency oracle fixtures")
        .map(|e| e.unwrap().path())
        .filter(|p| p.extension().is_some_and(|e| e == "txt"))
        .collect();
    paths.sort();
    assert!(paths.len() >= 16, "found {}", paths.len());
    let mut failures = Vec::new();
    let mut emergency = 0;
    for p in &paths {
        let (fx, case) = load(p);
        let warn = fs::read_to_string(p.with_extension("warn")).unwrap();
        if warn.lines().any(|l| l == "pass emergency") {
            emergency += 1;
        }
        let mt = Microtype { protrude_chars: case.protrude, adjust_spacing: case.adjust, items: case.micro.clone() };
        let (lines, mlines) = layout_paragraph_microtype(&case.items, &case.params, &mt).expect("layout");
        let (f, dx) = compare(&fx, &lines, Some(&mlines), &warn, 0.001);
        println!("{:<28} microtype  pass={} lines={} max_dx={dx:.5}pt {}", fx.name, lines.stats.pass, lines.lines.len(), f.join("; "));
        if !f.is_empty() {
            failures.push(format!("{} (microtype)", fx.name));
        }
        if case.protrude <= 0 && case.adjust <= 0 {
            let lines = layout_paragraph(&case.items, &case.params).expect("layout");
            let (f, dx) = compare(&fx, &lines, None, &warn, 0.1);
            println!("{:<28} plain      pass={} lines={} max_dx={dx:.5}pt {}", fx.name, lines.stats.pass, lines.lines.len(), f.join("; "));
            if !f.is_empty() {
                failures.push(format!("{} (plain)", fx.name));
            }
        }
    }
    println!("SUMMARY fixtures={} emergency_pass={emergency} failures={}", paths.len(), failures.len());
    assert!(emergency >= 8, "fixtures must exercise the emergency pass");
    assert!(failures.is_empty(), "{failures:?}");
}
