//! amssymb/amsfonts math symbols: the `AMSa` (msam) and `AMSb` (msbm)
//! declarations of `amssymb.sty`/`amsfonts.sty` (TeX Live 2026, v3.01), with
//! each command's math class and font slot, the Unicode text standing for it
//! and the OpenType face that carries that text.
//!
//! GENERATED by `scripts/gen_amssymb.py`; do not edit by hand. The TFM slot is
//! what pdfLaTeX sets: render-pipeline boxes every symbol from the msam/msbm
//! TFMs at its math size (math-layout `ams`) and paints `text` from the face;
//! `width_em` (msam10/msbm10) only feeds the compiler's own layout.

/// `AMSa` (`U/msa/m/n`, msam) or `AMSb` (`U/msb/m/n`, msbm).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SymbolFont {
    Msam,
    Msbm,
}

/// The `\math<class>` of the declaration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SymbolClass {
    Ord,
    Bin,
    Rel,
    Open,
    Close,
}

/// Which `\usepackage` a symbol needs to exist at all.
///
/// `amsfonts.sty` is loadable on its own and declares a subset;
/// `amssymb.sty` requires `amsfonts` and declares the rest, so `Amsfonts`
/// means "either package" and `Amssymb` means "`amssymb` only". Without the
/// declaring file base LaTeX2e has no definition for the command and
/// pdflatex answers "Undefined control sequence" (probed with `\ifcsname`
/// for every name, TeX Live 2025).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Provider {
    Amssymb,
    Amsfonts,
}

/// The face whose `cmap` carries every character of a symbol's `text`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Face {
    LatinModernMath,
    NewComputerModernMath,
    /// An empty `text`: a piece that paints nothing of its own.
    None,
}

#[derive(Debug, PartialEq)]
pub struct AmsSymbol {
    /// The command without its backslash; names containing `@` are pieces
    /// other constructions place, not commands.
    pub name: &'static str,
    /// Unicode text: one character, or a base followed by U+0338 when Unicode
    /// has no precomposed negation.
    pub text: &'static str,
    pub class: SymbolClass,
    pub font: SymbolFont,
    pub slot: u8,
    /// Character width in ems of msam10/msbm10.
    pub width_em: f64,
    pub face: Face,
    /// The package that has to be loaded for the command to exist.
    pub provider: Provider,
    /// The declaring `file:line`.
    pub source: &'static str,
}

pub const SYMBOLS: &[AmsSymbol] = &[
    AmsSymbol { name: "boxdot", text: "\u{22A1}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x00, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:44" },
    AmsSymbol { name: "boxplus", text: "\u{229E}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x01, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:45" },
    AmsSymbol { name: "boxtimes", text: "\u{22A0}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x02, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:46" },
    AmsSymbol { name: "square", text: "\u{25A1}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x03, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amssymb.sty:47" },
    AmsSymbol { name: "blacksquare", text: "\u{25A0}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x04, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:48" },
    AmsSymbol { name: "centerdot", text: "\u{2B1D}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x05, width_em: 0.277779, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:49" },
    AmsSymbol { name: "lozenge", text: "\u{25CA}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x06, width_em: 0.666669, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amssymb.sty:50" },
    AmsSymbol { name: "blacklozenge", text: "\u{29EB}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x07, width_em: 0.666669, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:51" },
    AmsSymbol { name: "circlearrowright", text: "\u{21BB}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x08, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:52" },
    AmsSymbol { name: "circlearrowleft", text: "\u{21BA}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x09, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:53" },
    AmsSymbol { name: "leftrightharpoons", text: "\u{21CB}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x0B, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:56" },
    AmsSymbol { name: "boxminus", text: "\u{229F}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x0C, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:57" },
    AmsSymbol { name: "Vdash", text: "\u{22A9}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x0D, width_em: 0.722224, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:58" },
    AmsSymbol { name: "Vvdash", text: "\u{22AA}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x0E, width_em: 0.888891, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:59" },
    AmsSymbol { name: "vDash", text: "\u{22A8}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x0F, width_em: 0.611113, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:60" },
    AmsSymbol { name: "twoheadrightarrow", text: "\u{21A0}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x10, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:61" },
    AmsSymbol { name: "twoheadleftarrow", text: "\u{219E}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x11, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:62" },
    AmsSymbol { name: "leftleftarrows", text: "\u{21C7}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x12, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:63" },
    AmsSymbol { name: "rightrightarrows", text: "\u{21C9}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x13, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:64" },
    AmsSymbol { name: "upuparrows", text: "\u{21C8}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x14, width_em: 0.833336, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:65" },
    AmsSymbol { name: "downdownarrows", text: "\u{21CA}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x15, width_em: 0.833336, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:66" },
    AmsSymbol { name: "upharpoonright", text: "\u{21BE}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x16, width_em: 0.416669, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:67" },
    AmsSymbol { name: "downharpoonright", text: "\u{21C2}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x17, width_em: 0.416669, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:69" },
    AmsSymbol { name: "upharpoonleft", text: "\u{21BF}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x18, width_em: 0.416669, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:70" },
    AmsSymbol { name: "downharpoonleft", text: "\u{21C3}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x19, width_em: 0.416669, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:71" },
    AmsSymbol { name: "rightarrowtail", text: "\u{21A3}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x1A, width_em: 1.111115, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:72" },
    AmsSymbol { name: "leftarrowtail", text: "\u{21A2}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x1B, width_em: 1.111115, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:73" },
    AmsSymbol { name: "leftrightarrows", text: "\u{21C6}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x1C, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:74" },
    AmsSymbol { name: "rightleftarrows", text: "\u{21C4}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x1D, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:75" },
    AmsSymbol { name: "Lsh", text: "\u{21B0}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x1E, width_em: 0.500002, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:76" },
    AmsSymbol { name: "Rsh", text: "\u{21B1}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x1F, width_em: 0.500002, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:77" },
    AmsSymbol { name: "rightsquigarrow", text: "\u{21DD}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x20, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amssymb.sty:78" },
    AmsSymbol { name: "leftrightsquigarrow", text: "\u{21AD}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x21, width_em: 1.388893, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:79" },
    AmsSymbol { name: "looparrowleft", text: "\u{21AB}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x22, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:80" },
    AmsSymbol { name: "looparrowright", text: "\u{21AC}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x23, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:81" },
    AmsSymbol { name: "circeq", text: "\u{2257}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x24, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:82" },
    AmsSymbol { name: "succsim", text: "\u{227F}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x25, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:83" },
    AmsSymbol { name: "gtrsim", text: "\u{2273}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x26, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:84" },
    AmsSymbol { name: "gtrapprox", text: "\u{2A86}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x27, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:85" },
    AmsSymbol { name: "multimap", text: "\u{22B8}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x28, width_em: 1.111115, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:86" },
    AmsSymbol { name: "therefore", text: "\u{2234}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x29, width_em: 0.666669, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:87" },
    AmsSymbol { name: "because", text: "\u{2235}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x2A, width_em: 0.666669, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:88" },
    AmsSymbol { name: "doteqdot", text: "\u{2251}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x2B, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:89" },
    AmsSymbol { name: "triangleq", text: "\u{225C}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x2C, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:91" },
    AmsSymbol { name: "precsim", text: "\u{227E}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x2D, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:92" },
    AmsSymbol { name: "lesssim", text: "\u{2272}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x2E, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:93" },
    AmsSymbol { name: "lessapprox", text: "\u{2A85}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x2F, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:94" },
    AmsSymbol { name: "eqslantless", text: "\u{2A95}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x30, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:95" },
    AmsSymbol { name: "eqslantgtr", text: "\u{2A96}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x31, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:96" },
    AmsSymbol { name: "curlyeqprec", text: "\u{22DE}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x32, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:97" },
    AmsSymbol { name: "curlyeqsucc", text: "\u{22DF}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x33, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:98" },
    AmsSymbol { name: "preccurlyeq", text: "\u{227C}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x34, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:99" },
    AmsSymbol { name: "leqq", text: "\u{2266}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x35, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:100" },
    AmsSymbol { name: "leqslant", text: "\u{2A7D}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x36, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:101" },
    AmsSymbol { name: "lessgtr", text: "\u{2276}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x37, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:102" },
    AmsSymbol { name: "backprime", text: "\u{2035}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x38, width_em: 0.275000, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:103" },
    AmsSymbol { name: "risingdotseq", text: "\u{2253}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x3A, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:104" },
    AmsSymbol { name: "fallingdotseq", text: "\u{2252}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x3B, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:105" },
    AmsSymbol { name: "succcurlyeq", text: "\u{227D}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x3C, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:106" },
    AmsSymbol { name: "geqq", text: "\u{2267}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x3D, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:107" },
    AmsSymbol { name: "geqslant", text: "\u{2A7E}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x3E, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:108" },
    AmsSymbol { name: "gtrless", text: "\u{2277}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x3F, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:109" },
    AmsSymbol { name: "vartriangleright", text: "\u{22B3}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x42, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amssymb.sty:113" },
    AmsSymbol { name: "vartriangleleft", text: "\u{22B2}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x43, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amssymb.sty:114" },
    AmsSymbol { name: "trianglerighteq", text: "\u{22B5}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x44, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amssymb.sty:115" },
    AmsSymbol { name: "trianglelefteq", text: "\u{22B4}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x45, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amssymb.sty:116" },
    AmsSymbol { name: "bigstar", text: "\u{2605}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x46, width_em: 0.944446, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:117" },
    AmsSymbol { name: "between", text: "\u{226C}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x47, width_em: 0.500002, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:118" },
    AmsSymbol { name: "blacktriangledown", text: "\u{25BE}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x48, width_em: 0.722224, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:119" },
    AmsSymbol { name: "blacktriangleright", text: "\u{25B6}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x49, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:120" },
    AmsSymbol { name: "blacktriangleleft", text: "\u{25C0}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x4A, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:121" },
    AmsSymbol { name: "vartriangle", text: "\u{25B5}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x4D, width_em: 0.722224, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:122" },
    AmsSymbol { name: "blacktriangle", text: "\u{25B4}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x4E, width_em: 0.722224, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:123" },
    AmsSymbol { name: "triangledown", text: "\u{25BF}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x4F, width_em: 0.722224, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:124" },
    AmsSymbol { name: "eqcirc", text: "\u{2256}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x50, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:125" },
    AmsSymbol { name: "lesseqgtr", text: "\u{22DA}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x51, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:126" },
    AmsSymbol { name: "gtreqless", text: "\u{22DB}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x52, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:127" },
    AmsSymbol { name: "lesseqqgtr", text: "\u{2A8B}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x53, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:128" },
    AmsSymbol { name: "gtreqqless", text: "\u{2A8C}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x54, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:129" },
    AmsSymbol { name: "Rrightarrow", text: "\u{21DB}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x56, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:130" },
    AmsSymbol { name: "Lleftarrow", text: "\u{21DA}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x57, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:131" },
    AmsSymbol { name: "veebar", text: "\u{22BB}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x59, width_em: 0.611113, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:132" },
    AmsSymbol { name: "barwedge", text: "\u{22BC}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x5A, width_em: 0.611113, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:133" },
    AmsSymbol { name: "doublebarwedge", text: "\u{2A5E}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x5B, width_em: 0.611113, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:134" },
    AmsSymbol { name: "measuredangle", text: "\u{2221}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x5D, width_em: 0.722224, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:137" },
    AmsSymbol { name: "sphericalangle", text: "\u{2222}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x5E, width_em: 0.722224, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:138" },
    AmsSymbol { name: "varpropto", text: "\u{221D}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x5F, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:139" },
    AmsSymbol { name: "smallsmile", text: "\u{2323}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x60, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:140" },
    AmsSymbol { name: "smallfrown", text: "\u{2322}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x61, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:141" },
    AmsSymbol { name: "Subset", text: "\u{22D0}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x62, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:142" },
    AmsSymbol { name: "Supset", text: "\u{22D1}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x63, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:143" },
    AmsSymbol { name: "Cup", text: "\u{22D3}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x64, width_em: 0.666669, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:144" },
    AmsSymbol { name: "Cap", text: "\u{22D2}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x65, width_em: 0.666669, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:146" },
    AmsSymbol { name: "curlywedge", text: "\u{22CF}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x66, width_em: 0.760417, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:148" },
    AmsSymbol { name: "curlyvee", text: "\u{22CE}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x67, width_em: 0.760417, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:149" },
    AmsSymbol { name: "leftthreetimes", text: "\u{22CB}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x68, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:150" },
    AmsSymbol { name: "rightthreetimes", text: "\u{22CC}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x69, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:151" },
    AmsSymbol { name: "subseteqq", text: "\u{2AC5}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x6A, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:152" },
    AmsSymbol { name: "supseteqq", text: "\u{2AC6}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x6B, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:153" },
    AmsSymbol { name: "bumpeq", text: "\u{224F}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x6C, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:154" },
    AmsSymbol { name: "Bumpeq", text: "\u{224E}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x6D, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:155" },
    AmsSymbol { name: "lll", text: "\u{22D8}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x6E, width_em: 1.333338, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:156" },
    AmsSymbol { name: "ggg", text: "\u{22D9}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x6F, width_em: 1.333338, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:158" },
    AmsSymbol { name: "circledS", text: "\u{24C8}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x73, width_em: 0.902219, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:160" },
    AmsSymbol { name: "pitchfork", text: "\u{22D4}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x74, width_em: 0.666669, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:161" },
    AmsSymbol { name: "dotplus", text: "\u{2214}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x75, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:162" },
    AmsSymbol { name: "backsim", text: "\u{223D}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x76, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:163" },
    AmsSymbol { name: "backsimeq", text: "\u{22CD}", class: SymbolClass::Rel, font: SymbolFont::Msam, slot: 0x77, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:164" },
    AmsSymbol { name: "complement", text: "\u{2201}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x7B, width_em: 0.500002, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:165" },
    AmsSymbol { name: "intercal", text: "\u{22BA}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x7C, width_em: 0.555557, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:166" },
    AmsSymbol { name: "circledcirc", text: "\u{229A}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x7D, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:167" },
    AmsSymbol { name: "circledast", text: "\u{229B}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x7E, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:168" },
    AmsSymbol { name: "circleddash", text: "\u{229D}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x7F, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:169" },
    AmsSymbol { name: "lvertneqq", text: "\u{2268}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x00, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:171" },
    AmsSymbol { name: "gvertneqq", text: "\u{2269}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x01, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:172" },
    AmsSymbol { name: "nleq", text: "\u{2270}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x02, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:173" },
    AmsSymbol { name: "ngeq", text: "\u{2271}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x03, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:174" },
    AmsSymbol { name: "nless", text: "\u{226E}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x04, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:175" },
    AmsSymbol { name: "ngtr", text: "\u{226F}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x05, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:176" },
    AmsSymbol { name: "nprec", text: "\u{2280}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x06, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:177" },
    AmsSymbol { name: "nsucc", text: "\u{2281}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x07, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:178" },
    AmsSymbol { name: "lneqq", text: "\u{2268}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x08, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:179" },
    AmsSymbol { name: "gneqq", text: "\u{2269}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x09, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:180" },
    AmsSymbol { name: "nleqslant", text: "\u{2A7D}\u{0338}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x0A, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:181" },
    AmsSymbol { name: "ngeqslant", text: "\u{2A7E}\u{0338}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x0B, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:182" },
    AmsSymbol { name: "lneq", text: "\u{2A87}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x0C, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:183" },
    AmsSymbol { name: "gneq", text: "\u{2A88}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x0D, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:184" },
    AmsSymbol { name: "npreceq", text: "\u{22E0}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x0E, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:185" },
    AmsSymbol { name: "nsucceq", text: "\u{22E1}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x0F, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:186" },
    AmsSymbol { name: "precnsim", text: "\u{22E8}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x10, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:187" },
    AmsSymbol { name: "succnsim", text: "\u{22E9}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x11, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:188" },
    AmsSymbol { name: "lnsim", text: "\u{22E6}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x12, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:189" },
    AmsSymbol { name: "gnsim", text: "\u{22E7}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x13, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:190" },
    AmsSymbol { name: "nleqq", text: "\u{2266}\u{0338}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x14, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:191" },
    AmsSymbol { name: "ngeqq", text: "\u{2267}\u{0338}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x15, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:192" },
    AmsSymbol { name: "precneqq", text: "\u{2AB5}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x16, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:193" },
    AmsSymbol { name: "succneqq", text: "\u{2AB6}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x17, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:194" },
    AmsSymbol { name: "precnapprox", text: "\u{2AB9}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x18, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:195" },
    AmsSymbol { name: "succnapprox", text: "\u{2ABA}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x19, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:196" },
    AmsSymbol { name: "lnapprox", text: "\u{2A89}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x1A, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:197" },
    AmsSymbol { name: "gnapprox", text: "\u{2A8A}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x1B, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:198" },
    AmsSymbol { name: "nsim", text: "\u{2241}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x1C, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:199" },
    AmsSymbol { name: "ncong", text: "\u{2247}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x1D, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:200" },
    AmsSymbol { name: "diagup", text: "\u{27CB}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x1E, width_em: 0.888891, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:201" },
    AmsSymbol { name: "diagdown", text: "\u{27CD}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x1F, width_em: 0.888891, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:202" },
    AmsSymbol { name: "varsubsetneq", text: "\u{228A}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x20, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:203" },
    AmsSymbol { name: "varsupsetneq", text: "\u{228B}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x21, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:204" },
    AmsSymbol { name: "nsubseteqq", text: "\u{2AC5}\u{0338}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x22, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:205" },
    AmsSymbol { name: "nsupseteqq", text: "\u{2AC6}\u{0338}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x23, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:206" },
    AmsSymbol { name: "subsetneqq", text: "\u{2ACB}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x24, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:207" },
    AmsSymbol { name: "supsetneqq", text: "\u{2ACC}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x25, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:208" },
    AmsSymbol { name: "varsubsetneqq", text: "\u{2ACB}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x26, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:209" },
    AmsSymbol { name: "varsupsetneqq", text: "\u{2ACC}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x27, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:210" },
    AmsSymbol { name: "subsetneq", text: "\u{228A}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x28, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:211" },
    AmsSymbol { name: "supsetneq", text: "\u{228B}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x29, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:212" },
    AmsSymbol { name: "nsubseteq", text: "\u{2288}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x2A, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:213" },
    AmsSymbol { name: "nsupseteq", text: "\u{2289}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x2B, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:214" },
    AmsSymbol { name: "nparallel", text: "\u{2226}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x2C, width_em: 0.500002, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:215" },
    AmsSymbol { name: "nmid", text: "\u{2224}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x2D, width_em: 0.277779, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:216" },
    AmsSymbol { name: "nshortmid", text: "\u{2224}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x2E, width_em: 0.222223, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:217" },
    AmsSymbol { name: "nshortparallel", text: "\u{2226}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x2F, width_em: 0.388890, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:218" },
    AmsSymbol { name: "nvdash", text: "\u{22AC}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x30, width_em: 0.611113, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:219" },
    AmsSymbol { name: "nVdash", text: "\u{22AE}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x31, width_em: 0.722224, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:220" },
    AmsSymbol { name: "nvDash", text: "\u{22AD}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x32, width_em: 0.611113, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:221" },
    AmsSymbol { name: "nVDash", text: "\u{22AF}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x33, width_em: 0.722224, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:222" },
    AmsSymbol { name: "ntrianglerighteq", text: "\u{22ED}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x34, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:223" },
    AmsSymbol { name: "ntrianglelefteq", text: "\u{22EC}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x35, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:224" },
    AmsSymbol { name: "ntriangleleft", text: "\u{22EA}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x36, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:225" },
    AmsSymbol { name: "ntriangleright", text: "\u{22EB}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x37, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:226" },
    AmsSymbol { name: "nleftarrow", text: "\u{219A}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x38, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:227" },
    AmsSymbol { name: "nrightarrow", text: "\u{219B}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x39, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:228" },
    AmsSymbol { name: "nLeftarrow", text: "\u{21CD}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x3A, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:229" },
    AmsSymbol { name: "nRightarrow", text: "\u{21CF}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x3B, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:230" },
    AmsSymbol { name: "nLeftrightarrow", text: "\u{21CE}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x3C, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:231" },
    AmsSymbol { name: "nleftrightarrow", text: "\u{21AE}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x3D, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:232" },
    AmsSymbol { name: "divideontimes", text: "\u{22C7}", class: SymbolClass::Bin, font: SymbolFont::Msbm, slot: 0x3E, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:233" },
    AmsSymbol { name: "varnothing", text: "\u{2205}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x3F, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:234" },
    AmsSymbol { name: "nexists", text: "\u{2204}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x40, width_em: 0.555557, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:235" },
    AmsSymbol { name: "Finv", text: "\u{2132}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x60, width_em: 0.555557, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:236" },
    AmsSymbol { name: "Game", text: "\u{2141}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x61, width_em: 0.638890, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:237" },
    AmsSymbol { name: "eth", text: "\u{00F0}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x67, width_em: 0.555557, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:240" },
    AmsSymbol { name: "eqsim", text: "\u{2242}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x68, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:241" },
    AmsSymbol { name: "beth", text: "\u{2136}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x69, width_em: 0.666669, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:242" },
    AmsSymbol { name: "gimel", text: "\u{2137}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x6A, width_em: 0.444446, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:243" },
    AmsSymbol { name: "daleth", text: "\u{2138}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x6B, width_em: 0.666669, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:244" },
    AmsSymbol { name: "lessdot", text: "\u{22D6}", class: SymbolClass::Bin, font: SymbolFont::Msbm, slot: 0x6C, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:245" },
    AmsSymbol { name: "gtrdot", text: "\u{22D7}", class: SymbolClass::Bin, font: SymbolFont::Msbm, slot: 0x6D, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:246" },
    AmsSymbol { name: "ltimes", text: "\u{22C9}", class: SymbolClass::Bin, font: SymbolFont::Msbm, slot: 0x6E, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:247" },
    AmsSymbol { name: "rtimes", text: "\u{22CA}", class: SymbolClass::Bin, font: SymbolFont::Msbm, slot: 0x6F, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:248" },
    AmsSymbol { name: "shortmid", text: "\u{2223}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x70, width_em: 0.222223, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:249" },
    AmsSymbol { name: "shortparallel", text: "\u{2225}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x71, width_em: 0.388890, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:250" },
    AmsSymbol { name: "smallsetminus", text: "\u{2216}", class: SymbolClass::Bin, font: SymbolFont::Msbm, slot: 0x72, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:251" },
    AmsSymbol { name: "thicksim", text: "\u{223C}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x73, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:252" },
    AmsSymbol { name: "thickapprox", text: "\u{2248}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x74, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:253" },
    AmsSymbol { name: "approxeq", text: "\u{224A}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x75, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:254" },
    AmsSymbol { name: "succapprox", text: "\u{2AB8}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x76, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:255" },
    AmsSymbol { name: "precapprox", text: "\u{2AB7}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x77, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:256" },
    AmsSymbol { name: "curvearrowleft", text: "\u{21B6}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x78, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:257" },
    AmsSymbol { name: "curvearrowright", text: "\u{21B7}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x79, width_em: 1.000003, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:258" },
    AmsSymbol { name: "digamma", text: "\u{03DD}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x7A, width_em: 0.777781, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:259" },
    AmsSymbol { name: "varkappa", text: "\u{03F0}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x7B, width_em: 0.666669, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:260" },
    AmsSymbol { name: "Bbbk", text: "\u{1D55C}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x7C, width_em: 0.555557, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:261" },
    AmsSymbol { name: "hslash", text: "\u{210F}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x7D, width_em: 0.540280, face: Face::LatinModernMath, provider: Provider::Amssymb, source: "amssymb.sty:262" },
    AmsSymbol { name: "backepsilon", text: "\u{03F6}", class: SymbolClass::Rel, font: SymbolFont::Msbm, slot: 0x7F, width_em: 0.429169, face: Face::NewComputerModernMath, provider: Provider::Amssymb, source: "amssymb.sty:265" },
    AmsSymbol { name: "ulcorner", text: "\u{231C}", class: SymbolClass::Open, font: SymbolFont::Msam, slot: 0x70, width_em: 0.500002, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:74" },
    AmsSymbol { name: "urcorner", text: "\u{231D}", class: SymbolClass::Close, font: SymbolFont::Msam, slot: 0x71, width_em: 0.500002, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:75" },
    AmsSymbol { name: "llcorner", text: "\u{231E}", class: SymbolClass::Open, font: SymbolFont::Msam, slot: 0x78, width_em: 0.500002, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:76" },
    AmsSymbol { name: "lrcorner", text: "\u{231F}", class: SymbolClass::Close, font: SymbolFont::Msam, slot: 0x79, width_em: 0.500002, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:77" },
    AmsSymbol { name: "mho", text: "\u{2127}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x66, width_em: 0.722224, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:101" },
    AmsSymbol { name: "lhd", text: "\u{22B2}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x43, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:157" },
    AmsSymbol { name: "unlhd", text: "\u{22B4}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x45, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:158" },
    AmsSymbol { name: "rhd", text: "\u{22B3}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x42, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:159" },
    AmsSymbol { name: "unrhd", text: "\u{22B5}", class: SymbolClass::Bin, font: SymbolFont::Msam, slot: 0x44, width_em: 0.777781, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:160" },
    AmsSymbol { name: "yen", text: "\u{00A5}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x55, width_em: 0.750002, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:64" },
    AmsSymbol { name: "checkmark", text: "\u{2713}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x58, width_em: 0.833336, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:67" },
    AmsSymbol { name: "circledR", text: "\u{00AE}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x72, width_em: 0.946663, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:70" },
    AmsSymbol { name: "maltese", text: "\u{2720}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x7A, width_em: 0.833336, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:73" },
    AmsSymbol { name: "dabar@", text: "", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x39, width_em: 0.500002, face: Face::None, provider: Provider::Amsfonts, source: "amsfonts.sty:89" },
    AmsSymbol { name: "dashrightarrow@", text: "\u{21E2}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x4B, width_em: 0.500002, face: Face::NewComputerModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:90" },
    AmsSymbol { name: "dashleftarrow@", text: "\u{21E0}", class: SymbolClass::Ord, font: SymbolFont::Msam, slot: 0x4C, width_em: 0.500002, face: Face::NewComputerModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:92" },
    AmsSymbol { name: "widehat@", text: "\u{0302}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x5B, width_em: 1.888895, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:81" },
    AmsSymbol { name: "widetilde@", text: "\u{0303}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x5D, width_em: 1.888895, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "amsfonts.sty:85" },
    AmsSymbol { name: "widehat@@", text: "\u{0302}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x5C, width_em: 2.333341, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "msbm10.tfm" },
    AmsSymbol { name: "widetilde@@", text: "\u{0303}", class: SymbolClass::Ord, font: SymbolFont::Msbm, slot: 0x5E, width_em: 2.333341, face: Face::LatinModernMath, provider: Provider::Amsfonts, source: "msbm10.tfm" },
];

/// `\global\let` aliases of `amssymb.sty` (68, 90, 145, 147, 157, 159).
pub const ALIASES: &[(&str, &str)] = &[
    ("restriction", "upharpoonright"),
    ("Doteq", "doteqdot"),
    ("doublecup", "Cup"),
    ("doublecap", "Cap"),
    ("llless", "lll"),
    ("gggtr", "ggg"),
    ("Box", "square"),
    ("Diamond", "lozenge"),
    ("leadsto", "rightsquigarrow"),
];

/// Advances (font units of 1000) of the Latin Modern Math characters above.
pub const LM_ADVANCES: &[(char, u16)] = &[
    ('\u{00A5}', 750),
    ('\u{00AE}', 683),
    ('\u{00F0}', 500),
    ('\u{0302}', 0),
    ('\u{0303}', 0),
    ('\u{0338}', 0),
    ('\u{03F0}', 624),
    ('\u{2035}', 311),
    ('\u{210F}', 576),
    ('\u{2127}', 722),
    ('\u{2136}', 604),
    ('\u{2137}', 528),
    ('\u{2138}', 574),
    ('\u{219A}', 997),
    ('\u{219B}', 997),
    ('\u{219E}', 1017),
    ('\u{21A0}', 1017),
    ('\u{21A2}', 1192),
    ('\u{21A3}', 1192),
    ('\u{21AB}', 997),
    ('\u{21AC}', 997),
    ('\u{21AD}', 996),
    ('\u{21AE}', 996),
    ('\u{21B0}', 564),
    ('\u{21B1}', 564),
    ('\u{21B6}', 980),
    ('\u{21B7}', 980),
    ('\u{21BA}', 771),
    ('\u{21BB}', 771),
    ('\u{21BE}', 441),
    ('\u{21BF}', 441),
    ('\u{21C2}', 441),
    ('\u{21C3}', 441),
    ('\u{21C4}', 1018),
    ('\u{21C6}', 1018),
    ('\u{21C7}', 997),
    ('\u{21C8}', 992),
    ('\u{21C9}', 997),
    ('\u{21CA}', 992),
    ('\u{21CB}', 1018),
    ('\u{21CD}', 991),
    ('\u{21CE}', 1068),
    ('\u{21CF}', 991),
    ('\u{21DA}', 1015),
    ('\u{21DB}', 1015),
    ('\u{21DD}', 997),
    ('\u{2201}', 556),
    ('\u{2204}', 556),
    ('\u{2205}', 500),
    ('\u{2214}', 778),
    ('\u{2216}', 568),
    ('\u{221D}', 778),
    ('\u{2221}', 778),
    ('\u{2222}', 778),
    ('\u{2223}', 278),
    ('\u{2224}', 388),
    ('\u{2225}', 500),
    ('\u{2226}', 556),
    ('\u{2234}', 516),
    ('\u{2235}', 516),
    ('\u{223C}', 773),
    ('\u{223D}', 773),
    ('\u{2241}', 773),
    ('\u{2242}', 778),
    ('\u{2247}', 778),
    ('\u{2248}', 773),
    ('\u{224A}', 778),
    ('\u{224E}', 778),
    ('\u{224F}', 778),
    ('\u{2251}', 778),
    ('\u{2252}', 778),
    ('\u{2253}', 778),
    ('\u{2256}', 778),
    ('\u{2257}', 778),
    ('\u{225C}', 778),
    ('\u{2266}', 778),
    ('\u{2267}', 778),
    ('\u{2268}', 778),
    ('\u{2269}', 778),
    ('\u{226C}', 434),
    ('\u{226E}', 778),
    ('\u{226F}', 778),
    ('\u{2270}', 778),
    ('\u{2271}', 778),
    ('\u{2272}', 776),
    ('\u{2273}', 776),
    ('\u{2276}', 778),
    ('\u{2277}', 778),
    ('\u{227C}', 738),
    ('\u{227D}', 738),
    ('\u{227E}', 773),
    ('\u{227F}', 773),
    ('\u{2280}', 778),
    ('\u{2281}', 778),
    ('\u{2288}', 778),
    ('\u{2289}', 778),
    ('\u{228A}', 778),
    ('\u{228B}', 778),
    ('\u{229A}', 796),
    ('\u{229B}', 796),
    ('\u{229D}', 796),
    ('\u{229E}', 778),
    ('\u{229F}', 778),
    ('\u{22A0}', 778),
    ('\u{22A1}', 778),
    ('\u{22A8}', 612),
    ('\u{22A9}', 673),
    ('\u{22AA}', 841),
    ('\u{22AC}', 565),
    ('\u{22AD}', 732),
    ('\u{22AE}', 793),
    ('\u{22AF}', 773),
    ('\u{22B2}', 738),
    ('\u{22B3}', 738),
    ('\u{22B4}', 738),
    ('\u{22B5}', 738),
    ('\u{22B8}', 948),
    ('\u{22BA}', 778),
    ('\u{22BB}', 642),
    ('\u{22BC}', 642),
    ('\u{22C7}', 802),
    ('\u{22C9}', 623),
    ('\u{22CA}', 623),
    ('\u{22CB}', 623),
    ('\u{22CC}', 623),
    ('\u{22CD}', 778),
    ('\u{22CE}', 733),
    ('\u{22CF}', 733),
    ('\u{22D0}', 698),
    ('\u{22D1}', 698),
    ('\u{22D2}', 658),
    ('\u{22D3}', 658),
    ('\u{22D6}', 778),
    ('\u{22D7}', 778),
    ('\u{22D8}', 1285),
    ('\u{22D9}', 1285),
    ('\u{22DA}', 778),
    ('\u{22DB}', 778),
    ('\u{22DE}', 738),
    ('\u{22DF}', 738),
    ('\u{22E0}', 738),
    ('\u{22E1}', 738),
    ('\u{22E6}', 776),
    ('\u{22E7}', 776),
    ('\u{22E8}', 773),
    ('\u{22E9}', 773),
    ('\u{22EA}', 738),
    ('\u{22EB}', 738),
    ('\u{22EC}', 738),
    ('\u{22ED}', 738),
    ('\u{231C}', 392),
    ('\u{231D}', 392),
    ('\u{231E}', 392),
    ('\u{231F}', 392),
    ('\u{2322}', 1000),
    ('\u{2323}', 1000),
    ('\u{25A0}', 778),
    ('\u{25A1}', 778),
    ('\u{25B6}', 858),
    ('\u{25C0}', 858),
    ('\u{25CA}', 572),
    ('\u{2713}', 833),
    ('\u{2720}', 796),
    ('\u{2A7D}', 778),
    ('\u{2A7E}', 778),
    ('\u{2A85}', 776),
    ('\u{2A86}', 776),
    ('\u{2A87}', 778),
    ('\u{2A88}', 778),
    ('\u{2A89}', 776),
    ('\u{2A8A}', 776),
    ('\u{2A8B}', 778),
    ('\u{2A8C}', 778),
    ('\u{2A95}', 778),
    ('\u{2A96}', 778),
    ('\u{1D55C}', 544),
];

/// Advances of the characters only New Computer Modern Math carries.
pub const NEWCM_ADVANCES: &[(char, u16)] = &[
    ('\u{03DD}', 500),
    ('\u{03F6}', 414),
    ('\u{2132}', 653),
    ('\u{2141}', 667),
    ('\u{21E0}', 1000),
    ('\u{21E2}', 1000),
    ('\u{22D4}', 839),
    ('\u{24C8}', 1124),
    ('\u{25B4}', 626),
    ('\u{25B5}', 626),
    ('\u{25BE}', 626),
    ('\u{25BF}', 626),
    ('\u{2605}', 827),
    ('\u{27CB}', 623),
    ('\u{27CD}', 623),
    ('\u{29EB}', 778),
    ('\u{2A5E}', 667),
    ('\u{2AB5}', 778),
    ('\u{2AB6}', 778),
    ('\u{2AB7}', 776),
    ('\u{2AB8}', 776),
    ('\u{2AB9}', 776),
    ('\u{2ABA}', 776),
    ('\u{2AC5}', 698),
    ('\u{2AC6}', 698),
    ('\u{2ACB}', 698),
    ('\u{2ACC}', 698),
    ('\u{2B1D}', 316),
];

/// The symbol a command names (aliases resolved); `None` for anything else,
/// including the `@` pieces.
pub fn by_name(name: &str) -> Option<&'static AmsSymbol> {
    if name.contains('@') {
        return None;
    }
    let name = ALIASES
        .iter()
        .find(|(alias, _)| *alias == name)
        .map_or(name, |(_, target)| *target);
    SYMBOLS.iter().find(|s| s.name == name)
}

/// A piece by its internal `@` name (`dabar@`, `widehat@`, ...).
pub fn piece(name: &str) -> Option<&'static AmsSymbol> {
    SYMBOLS.iter().find(|s| s.name == name)
}

/// The symbol set from a font slot.
pub fn by_slot(font: SymbolFont, slot: u8) -> Option<&'static AmsSymbol> {
    SYMBOLS.iter().find(|s| s.font == font && s.slot == slot)
}

/// Every command the table answers, aliases included.
pub fn command_names() -> impl Iterator<Item = &'static str> {
    SYMBOLS
        .iter()
        .map(|s| s.name)
        .filter(|n| !n.contains('@'))
        .chain(ALIASES.iter().map(|(alias, _)| *alias))
}

/// Advance of a Latin Modern Math character of this table.
pub fn lm_advance(c: char) -> Option<u16> {
    LM_ADVANCES.iter().find(|(g, _)| *g == c).map(|(_, a)| *a)
}

/// Advance of a character only New Computer Modern Math carries.
pub fn newcm_advance(c: char) -> Option<u16> {
    NEWCM_ADVANCES.iter().find(|(g, _)| *g == c).map(|(_, a)| *a)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The four latexsym names `amsfonts.sty` 157-160 re-declares on slots
    /// `amssymb.sty` 113-116 already uses, paired with the relation that holds
    /// the slot. Same font, same slot, same character — a different
    /// `\math<class>`, which is the whole point of the re-declaration.
    const LATEXSYM_REDECLARED: &[(&str, &str)] = &[
        ("lhd", "vartriangleleft"),
        ("unlhd", "trianglelefteq"),
        ("rhd", "vartriangleright"),
        ("unrhd", "trianglerighteq"),
    ];

    #[test]
    fn slots_are_unique_and_every_text_has_a_bound_face() {
        for (i, s) in SYMBOLS.iter().enumerate() {
            let redeclares = LATEXSYM_REDECLARED
                .iter()
                .any(|(latexsym, _)| *latexsym == s.name);
            assert!(
                redeclares || SYMBOLS[..i].iter().all(|t| (t.font, t.slot) != (s.font, s.slot)),
                "\\{} repeats a slot",
                s.name
            );
            assert!(
                SYMBOLS[..i].iter().all(|t| t.name != s.name),
                "\\{} listed twice",
                s.name
            );
            for c in s.text.chars() {
                let bound = match s.face {
                    Face::LatinModernMath => lm_advance(c).is_some(),
                    Face::NewComputerModernMath => {
                        newcm_advance(c).is_some() || lm_advance(c).is_some()
                    }
                    Face::None => false,
                };
                assert!(bound, "\\{} text {c:?} has no advance entry", s.name);
            }
            assert_eq!(s.text.is_empty(), s.face == Face::None, "\\{}", s.name);
        }
    }

    #[test]
    fn declarations_and_aliases_resolve() {
        let leq = by_name("leqslant").expect("amssymb.sty:101");
        assert_eq!((leq.font, leq.slot, leq.class), (SymbolFont::Msam, 0x36, SymbolClass::Rel));
        assert_eq!(by_name("restriction").map(|s| s.name), Some("upharpoonright"));
        assert_eq!(by_name("doublecup").map(|s| s.slot), Some(0x64));
        assert!(by_name("dabar@").is_none());
        assert_eq!(piece("widehat@").map(|s| s.slot), Some(0x5B));
        assert_eq!(by_slot(SymbolFont::Msbm, 0x02).map(|s| s.name), Some("nleq"));
        let ul = by_name("ulcorner").expect("amsfonts.sty:74");
        assert_eq!(ul.class, SymbolClass::Open);
    }

    /// The nine latexsym symbols `amsfonts.sty` provides itself when latexsym
    /// is not loaded (lines 101 and 150-162), measured against TeX Live 2025
    /// pdflatex at 10pt. `\Join` is a composite and has no row; the other
    /// eight resolve here, five as declarations and three as `\global\let`
    /// aliases.
    #[test]
    fn the_latexsym_symbols_keep_their_kernel_classes() {
        // amsfonts re-declares the four triangles as `\mathbin` on the AMSa
        // slots rather than letting them to the `\vartriangle*` relations,
        // which is what keeps latexsym's Bin class. Aliasing to the relation
        // name would be the same glyph one class out: measured at 10pt,
        // `$a\lhd b$` is 4.44433pt of glue wider than `$ab$` (Bin) against
        // `$a\vartriangleleft b$`'s 5.55542 (Rel).
        for (latexsym, relation) in LATEXSYM_REDECLARED {
            let bin = by_name(latexsym).expect("amsfonts.sty 157-160");
            let rel = by_name(relation).expect("amssymb.sty 113-116");
            assert_eq!((bin.font, bin.slot), (rel.font, rel.slot), "\\{latexsym}");
            assert_eq!(bin.text, rel.text, "\\{latexsym}");
            assert_eq!(bin.class, SymbolClass::Bin, "\\{latexsym}");
            assert_eq!(rel.class, SymbolClass::Rel, "\\{relation}");
            assert_eq!(bin.provider, Provider::Amsfonts, "\\{latexsym}");
        }
        // `amsfonts.sty` 101 declares `\mho` outside the latexsym guard and
        // `amssymb.sty` 239 has it commented out, so amsfonts alone provides
        // it — measured: `\usepackage{amsfonts}` gives 7.22223pt Ord, the
        // same advance as lasy10's.
        let mho = by_name("mho").expect("amsfonts.sty:101");
        assert_eq!(
            (mho.font, mho.slot, mho.class, mho.provider),
            (SymbolFont::Msbm, 0x66, SymbolClass::Ord, Provider::Amsfonts)
        );
        // amsfonts.sty 150-152 `\global\let`s the remaining three.
        for (alias, target, class) in [
            ("Box", "square", SymbolClass::Ord),
            ("Diamond", "lozenge", SymbolClass::Ord),
            ("leadsto", "rightsquigarrow", SymbolClass::Rel),
        ] {
            let s = by_name(alias).expect("amsfonts.sty 150-152");
            assert_eq!(s.name, target, "\\{alias}");
            assert_eq!(s.class, class, "\\{alias}");
            assert_eq!(s.provider, Provider::Amsfonts, "\\{alias}");
        }
    }
}
