//! The LaTeX this compiler implements, as data.
//!
//! `flashtex-compiler --supported [json|markdown|coverage]` prints this
//! inventory. The names are not a hand-maintained promise: text commands come
//! from `parser::BUILT_INS`, math symbols from `math::COMMAND_GLYPHS`,
//! operator names from `math::OPERATOR_NAMES` and math grids from
//! `math::GRID_ENVIRONMENTS`. The dispatch arms that have no constant of their
//! own (math structures, text environments, layout-neutral packages) are
//! listed below, and `tests/supported_latex.rs` scans the real `match` arms in
//! `src/parser.rs` and `src/math.rs` so the two cannot drift. The same test
//! compiles every listed name through the protocol and fails if any of them
//! produces a "not supported" diagnostic, and checks that the generated
//! `docs/user/compiler.md` section and `supported/*` files are current.
//!
//! Coverage is measured against `supported/canonical-latex.tsv`, a vendored
//! list regenerated by `scripts/canonical_latex.py` from the LaTeX2e
//! reference manual index and the package sources, confirmed by pdfLaTeX.
//! "Supported" means "handled without an unsupported diagnostic"; it is not a
//! claim of typographic fidelity (see the descriptions for approximations).

use crate::json::{write_number_into, write_string_into};
use crate::{math, parser};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Mode {
    Text,
    Math,
}

impl Mode {
    pub fn as_str(self) -> &'static str {
        match self {
            Mode::Text => "text",
            Mode::Math => "math",
        }
    }
}

/// Where in the compiler a command is recognised.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Origin {
    /// A `parser::Parser::command` dispatch arm.
    TextDispatch,
    /// `parser::style_command` / `parser::style_declaration` (face).
    TextStyle,
    /// A font-size declaration (`\tiny` .. `\Huge`).
    TextSize,
    /// Recognised by the lexer or the math atom reader, not by name dispatch.
    ControlSymbol,
    /// A `math::MathParser::command_atom` arm or an infix/limits switch.
    MathStructure,
    /// `math::COMMAND_GLYPHS`.
    MathSymbol,
    /// `math::OPERATOR_NAMES`.
    MathOperator,
    /// Executed by the expansion pass (`crate::expansion`): a TeX/LaTeX
    /// primitive or kernel macro of `flashtex-tex-expansion`, never seen by
    /// the parser.
    Expansion,
}

impl Origin {
    pub fn as_str(self) -> &'static str {
        match self {
            Origin::TextDispatch => "text_dispatch",
            Origin::TextStyle => "text_style",
            Origin::TextSize => "text_size",
            Origin::ControlSymbol => "control_symbol",
            Origin::MathStructure => "math_structure",
            Origin::MathSymbol => "math_symbol",
            Origin::MathOperator => "math_operator",
            Origin::Expansion => "expansion",
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Command {
    /// Without the backslash; the line break `\\` is the name `\`.
    pub name: &'static str,
    pub mode: Mode,
    pub origin: Origin,
    /// Argument shape, e.g. `{key}` or `[options]{class}`.
    pub arguments: &'static str,
    pub description: String,
    pub glyph: Option<&'static str>,
    /// False for arms that parse the command but always diagnose that its
    /// output is unavailable (`\check`, `\breve`); excluded from coverage.
    pub renders: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Environment {
    pub name: &'static str,
    pub mode: Mode,
    pub description: String,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Package {
    pub name: &'static str,
    /// The options under which loading the package is silent.
    pub options: &'static str,
    pub description: &'static str,
}

pub struct Inventory {
    pub commands: Vec<Command>,
    pub environments: Vec<Environment>,
    pub packages: Vec<Package>,
}

/// Text commands that have a dispatch arm but only ever emit a diagnostic.
///
/// `thanks` and `and` are meaningful only inside a `\title`/`\author`/`\date`
/// argument, where `strip_thanks` and the `\and` author split consume them.
/// They used to sit in a separate `TEXT_CONTEXT_ONLY` list documented as
/// "on their own they are diagnosed", which was not true: neither had an arm,
/// so both reached `parser::P::unsupported`, whose `debug_assert` on
/// `BUILT_INS` panicked the debug build instead. They now have arms that
/// really do diagnose, which is what this list means.
///
/// `today` was in that list too, and was wrong for a further reason: it
/// renders in ordinary body text like any other kernel macro, so it is an
/// inventory entry rather than a diagnostic.
pub const TEXT_DIAGNOSTIC_ONLY: &[&str] = &["frac", "sqrt", "thanks", "and"];

/// Dispatch arms that are not `parser::BUILT_INS` entries.
const TEXT_EXTRA_ARMS: &[&str] = &["newtheorem", "theoremstyle"];

/// Canonical commands the expansion pass executes itself (engine primitives
/// and kernel-prelude macros of `flashtex-tex-expansion`); their effect
/// reaches the parser only as expanded tokens. `\newcommand`/`\renewcommand`
/// and `\DeclareMathOperator` keep their parser-inventory entries.
const EXPANSION_COMMANDS: &[(&str, &str, &str)] = &[
    ("long", "", "prefix: the following definition accepts \\par in arguments"),
    ("protected", "", "e-TeX prefix: the following macro is not expanded inside \\edef-like contexts"),
    ("providecommand", "{\\name}[n][default]{body}", "defines the macro only when \\name is undefined"),
    ("DeclareRobustCommand", "{\\name}[n][default]{body}", "defines or redefines a macro (robustness is not modelled separately)"),
    ("newenvironment", "{env}[n][default]{begin}{end}", "defines an environment run by \\begin{env}/\\end{env}"),
    ("renewenvironment", "{env}[n][default]{begin}{end}", "redefines an environment"),
    ("newcounter", "{counter}[within]", "allocates a counter (\\c@counter, \\thecounter) reset by within"),
    ("setcounter", "{counter}{number}", "sets a counter globally"),
    ("addtocounter", "{counter}{number}", "adds to a counter globally"),
    ("stepcounter", "{counter}", "increments a counter and resets its dependants"),
    ("refstepcounter", "{counter}", "increments a counter and makes it the current \\label value"),
    ("value", "{counter}", "a counter's value in a number context"),
    ("Alph", "{counter}", "a counter as an upper-case letter"),
    ("fnsymbol", "{counter}", "a counter as a footnote symbol"),
    ("newlength", "{\\name}", "allocates a skip register"),
    ("settowidth", "{\\name}{text}", "sets a length from text measured by the expansion pass's box measurer (an approximation)"),
    ("settoheight", "{\\name}{text}", "sets a length from text height (an approximation, as \\settowidth)"),
    ("settodepth", "{\\name}{text}", "sets a length from text depth (an approximation, as \\settowidth)"),
    ("AtBeginDocument", "{code}", "stores code that runs at \\begin{document}"),
    ("AtEndDocument", "{code}", "stores code that runs at \\end{document}"),
    ("makeatother", "", "makes @ an other character again"),
    ("space", "", "expands to one space"),
    ("ignorespaces", "", "skips the spaces that follow"),
    ("jobname", "", "expands to texput"),
];

/// (name, arguments, description) for every `parser::BUILT_INS` entry that
/// renders, plus the lexer's `\\`.
const TEXT_COMMANDS: &[(&str, &str, &str)] = &[
    ("documentclass", "[options]{class}", "records the class and its 10pt/11pt/12pt size option; only the document body is typeset"),
    ("usepackage", "[options]{a,b,c}", "records packages; layout-neutral ones are silent, every other package warns that it is not implemented"),
    ("definecolor", "[class]{name}{model}{spec}", "colour definition in rgb, cmy, cmyk, gray, RGB, HTML or Gray (model lists pick the target model)"),
    ("providecolor", "[class]{name}{model}{spec}", "\\definecolor unless the colour is already defined"),
    ("xdefinecolor", "[class]{name}{model}{spec}", "xcolor synonym of \\definecolor"),
    ("colorlet", "[class]{name}[model]{expression}", "names an xcolor expression, optionally converted to a model"),
    ("definecolorset", "[class]{models}{head}{tail}{set}", "defines name,spec;... colours in one go"),
    ("DefineNamedColor", "{named}{name}{model}{spec}", "driver named colour, as dvipsnam.def uses it"),
    ("selectcolormodel", "{model}", "xcolor target model: natural, rgb, cmy, cmyk or gray"),
    ("color", "[model]{expression}", "text colour for the rest of the group; pdfTeX's exact operator values"),
    ("textcolor", "[model]{expression}{text}", "text in a colour"),
    ("pagecolor", "[model]{expression}", "page background colour, document-wide"),
    ("nopagecolor", "", "removes the page background colour"),
    ("normalcolor", "", "back to the default text colour"),
    ("colorbox", "[model]{expression}{text}", "text on a filled box \\fboxsep larger than its content"),
    ("fcolorbox", "[model]{frame}{fill}{text}", "\\colorbox inside a \\fboxrule frame"),
    ("setlength", "{\\length}{dimension}", "preamble page geometry and \\parskip; \\parindent of 0pt; other lengths warn"),
    ("addtolength", "{\\length}{dimension}", "preamble page geometry and \\parskip; accumulates onto the current value"),
    ("setlist", "[list]{options}", "enumitem keys recorded on every matching list; itemsep and topsep also set the built-in layout, other keys warn"),
    ("newcolumntype", "{X}[n]{spec}", "array column type expanded in later tabular specifications"),
    ("arrayrulecolor", "[model]{colour}", "colortbl: colour of later table rules"),
    ("doublerulesepcolor", "[model]{colour}", "colortbl: colour of the gap between double rules"),
    ("arraybackslash", "", "array no-op: \\\\ already ends the row inside p, m and b entries"),
    ("newcommand", "{\\name}[n]{body}", "defines a macro with 0-9 arguments; rejects an existing name"),
    ("renewcommand", "{\\name}[n]{body}", "redefines an existing macro"),
    ("DeclareMathOperator", "*{\\name}{text}", "defines \\name as \\operatorname{text}; the starred form takes limits"),
    ("begin", "{env}", "opens a supported environment"),
    ("end", "{env}", "closes the innermost open environment"),
    ("input", "{path}", "expands a project-relative document in place"),
    ("include", "{path}", "expands a project-relative document in place"),
    ("listfiles", "", "accepted no-op; there is no log stream"),
    ("section", "{...}", "numbered section heading; starred form unnumbered"),
    ("subsection", "{...}", "numbered subsection heading; starred form unnumbered"),
    ("label", "{key}", "names the current section, equation or figure number"),
    ("ref", "{key}", "number of the labelled item"),
    ("pageref", "{key}", "page number of the labelled item"),
    ("cref", "*{key list}", "cleveref lower-case named references; consecutive ranges are compressed"),
    ("Cref", "*{key list}", "cleveref capitalised named references; consecutive ranges are compressed"),
    ("crefrange", "*{first}{last}", "cleveref named reference range"),
    ("Crefrange", "*{first}{last}", "capitalised cleveref named reference range"),
    ("cpageref", "*{key list}", "cleveref named page references"),
    ("Cpageref", "*{key list}", "capitalised cleveref named page references"),
    ("labelcref", "*{key list}", "cleveref label text without the reference name"),
    ("crefname", "{type}{singular}{plural}", "cleveref lower-case singular and plural name override"),
    ("Crefname", "{type}{singular}{plural}", "cleveref capitalised singular and plural name override"),
    ("caption", "{...}", "numbered \"Figure N:\" caption inside figure"),
    ("item", "[label]", "entry of an itemize, enumerate or description list"),
    ("textbf", "{...}", "bold text"),
    ("textmd", "{...}", "medium-weight text"),
    ("textit", "{...}", "italic text"),
    ("textsl", "{...}", "slanted text (typeset as italic)"),
    ("textsc", "{...}", "small capitals (upright in the Core 14 layout)"),
    ("textup", "{...}", "upright text"),
    ("emph", "{...}", "emphasis: toggles italic"),
    ("texttt", "{...}", "typewriter text"),
    ("textrm", "{...}", "roman text"),
    ("textsf", "{...}", "sans-serif text"),
    ("textnormal", "{...}", "normal text face"),
    ("bfseries", "", "switches to bold"),
    ("mdseries", "", "switches to medium weight"),
    ("itshape", "", "switches to italic"),
    ("slshape", "", "switches to slanted (typeset as italic)"),
    ("scshape", "", "switches to small capitals (upright in the Core 14 layout)"),
    ("upshape", "", "switches to upright"),
    ("ttfamily", "", "switches to typewriter"),
    ("rmfamily", "", "switches to roman"),
    ("sffamily", "", "switches to sans-serif"),
    ("normalfont", "", "resets the text face"),
    ("em", "", "toggles emphasis"),
    ("bf", "", "LaTeX 2.09 form: bold roman"),
    ("it", "", "LaTeX 2.09 form: italic roman"),
    ("sl", "", "LaTeX 2.09 form: slanted roman"),
    ("sc", "", "LaTeX 2.09 form: small-caps roman (upright in the Core 14 layout)"),
    ("tt", "", "LaTeX 2.09 form: upright typewriter"),
    ("rm", "", "LaTeX 2.09 form: upright roman"),
    ("sf", "", "LaTeX 2.09 form: upright sans-serif"),
    ("tiny", "", "size declaration from the class size table"),
    ("scriptsize", "", "size declaration from the class size table"),
    ("footnotesize", "", "size declaration from the class size table"),
    ("small", "", "size declaration from the class size table"),
    ("normalsize", "", "size declaration: the active body size"),
    ("large", "", "size declaration from the class size table"),
    ("Large", "", "size declaration from the class size table"),
    ("LARGE", "", "size declaration from the class size table"),
    ("huge", "", "size declaration from the class size table"),
    ("Huge", "", "size declaration from the class size table"),
    ("par", "", "ends the paragraph"),
    ("hfill", "", "infinite-stretch horizontal glue"),
    ("hrulefill", "", "\\hfill filled with a 0.4pt baseline rule (latex.ltx \\leaders\\hrule\\hfill)"),
    ("dotfill", "", "\\hfill filled with dots in 0.44em boxes, centred (latex.ltx \\cleaders)"),
    ("hfil", "", "infinite-stretch horizontal glue (same order as \\hfill)"),
    ("hspace", "{dimension}", "fixed horizontal space; starred form identical"),
    ("quad", "", "1em of horizontal space"),
    ("qquad", "", "2em of horizontal space"),
    ("bigskip", "", "ends the paragraph and adds 12pt of vertical space"),
    ("medskip", "", "ends the paragraph and adds 6pt of vertical space"),
    ("smallskip", "", "ends the paragraph and adds 3pt of vertical space"),
    ("vspace", "{dimension}", "ends the paragraph and adds fixed vertical space"),
    ("hrule", "", "full-measure horizontal rule"),
    ("newpage", "", "forces a page break"),
    ("pagestyle", "{style}", "accepted; no headers or footers are rendered"),
    ("noindent", "", "accepted no-op; paragraphs are never indented"),
    ("subsubsection", "{...}", "numbered subsubsection heading; starred form unnumbered"),
    ("paragraph", "{...}", "run-in heading: bold, flush, set into the first line of the paragraph that follows it"),
    ("subparagraph", "{...}", "run-in heading indented by \\parindent, set into the first line of the paragraph that follows it"),
    ("tableofcontents", "", "article contents list from the previous layout pass"),
    ("eqref", "{key}", "parenthesised equation number of the labelled item"),
    ("numberwithin", "[\\style]{counter}{parent}", "amsmath: counter reset by parent and printed \\theparent.\\style{counter} (equation, figure, table; theorem counters within section)"),
    ("counterwithin", "{counter}{parent}", "counter reset by parent and printed \\theparent.\\arabic{counter}; starred form keeps the printed form"),
    ("counterwithout", "{counter}{parent}", "undoes \\counterwithin; starred form keeps the printed form"),
    ("hypersetup", "{key=value,...}", "hyperref options; PDF annotations, outline and metadata only, so nothing is typeset for them"),
    ("lstset", "{key=value,...}", "listings defaults, global from that point on; the key names are checked and nothing is typeset here"),
    ("url", "{url}", "monospaced URL text, breaking as url.sty does; links are not clickable"),
    ("href", "{url}{text}", "link text; links are not clickable"),
    ("nolinkurl", "{url}", "monospaced URL text without a link, breaking as url.sty does"),
    ("footnote", "[n]{...}", "numbered mark and page-bottom footnote text"),
    ("footnotemark", "[n]", "footnote mark only"),
    ("footnotetext", "[n]{...}", "footnote text without a mark"),
    ("includegraphics", "*[keys]{file}", "image box in running text (graphicx keys as written)"),
    ("scalebox", "{x}[y]{...}", "graphics.sty scaled box of the content"),
    ("resizebox", "*{width}{height}{...}", "graphics.sty box scaled to a width and/or height; ! keeps the aspect ratio"),
    ("rotatebox", "[keys]{angle}{...}", "graphicx rotated box; the box is the rotated bounding box"),
    ("reflectbox", "{...}", "graphics.sty box mirrored left to right"),
    ("graphicspath", "{{dir/}...}", "image search directories; no material"),
    ("allowdisplaybreaks", "[0-4]", "amsmath page-break permission inside displays; no material"),
    ("clearpage", "", "forces a page break"),
    ("cleardoublepage", "", "forces a page break (one-sided article)"),
    ("c", "{letter}", "cedilla text accent: the precomposed character the dfu tables declare (tex-text-encoding); without one the bare letter and a warning"),
    ("v", "{letter}", "caron text accent: the precomposed character the dfu tables declare (tex-text-encoding); without one the bare letter and a warning"),
    ("u", "{letter}", "breve text accent: the precomposed character the dfu tables declare (tex-text-encoding); without one the bare letter and a warning"),
    ("H", "{letter}", "double acute text accent: the precomposed character the dfu tables declare (tex-text-encoding); without one the bare letter and a warning"),
    ("r", "{letter}", "ring text accent: the precomposed character the dfu tables declare (tex-text-encoding); without one the bare letter and a warning"),
    ("k", "{letter}", "ogonek text accent (T1 only; OT1 reports it unavailable): the precomposed character the dfu tables declare; without one the bare letter and a warning"),
    ("d", "{letter}", "dot-below text accent: the precomposed character the dfu tables declare (tex-text-encoding); without one the bare letter and a warning"),
    ("b", "{letter}", "bar-below text accent: no dfu declarations, so the bare letter and a warning"),
    ("capitalcaron", "{letter}", "capital caron text accent: an alias of \\v, the precomposed character the dfu tables declare"),
    ("capitalbreve", "{letter}", "capital breve text accent: an alias of \\u, the precomposed character the dfu tables declare"),
    ("capitalring", "{letter}", "capital ring text accent: an alias of \\r, the precomposed character the dfu tables declare"),
    ("capitalogonek", "{letter}", "capital ogonek text accent: an alias of \\k (T1 only; OT1 reports it unavailable)"),
    ("capitalhungarumlaut", "{letter}", "capital double-acute text accent: an alias of \\H, the precomposed character the dfu tables declare"),
    ("capitalcedilla", "{letter}", "capital cedilla text accent: an alias of \\c, the precomposed character the dfu tables declare"),
    ("TeX", "", "latex.ltx logo: T, kern -.1667em, E lowered .5ex, kern -.125em, X"),
    ("LaTeX", "", "latex.ltx logo: L, kern -.36em, script-size A raised to the T height, kern -.15em, \\TeX"),
    ("LaTeXe", "", "\\LaTeX, kern .15em, 2 and a text-style subscript varepsilon"),
    ("rule", "[raise]{dimension}{dimension}", "filled rule box; pt/in/cm/mm/bp/dd/cc/pc/sp, em, ex, \\textwidth, \\linewidth, \\columnwidth"),
    ("uline", "{...}", "ulem underline: 0.4pt rule under the argument (single-line; needs ulem)"),
    ("underline", "{...}", "kernel text underline: TeXbook Rule 10 math-rule under an unbreakable hbox"),
    ("sout", "{...}", "ulem strike-out: 0.4pt rule 0.55ex above the baseline (single-line; needs ulem)"),
    ("thinspace", "", "text kern .16667em (math: thin muskip)"),
    ("negthinspace", "", "text kern -.16667em"),
    ("medspace", "", "text kern .2222em"),
    ("negmedspace", "", "text kern -.2222em"),
    ("thickspace", "", "text kern .2777em"),
    ("negthickspace", "", "text kern -.2777em"),
    ("enspace", "", "text kern .5em"),
    ("enskip", "", "horizontal glue of .5em"),
    ("pagebreak", "[n]", "page-break penalty -\\@getpen{n} (4: a forced break); in a paragraph, after the line it is set on"),
    ("nopagebreak", "[n]", "page-break penalty \\@getpen{n}; in a paragraph, after the line it is set on"),
    ("linebreak", "[n]", "line-break penalty -\\@getpen{n} (4: a forced break, the line stays justified)"),
    ("nolinebreak", "[n]", "line-break penalty \\@getpen{n}, the space before it moved after it"),
    ("penalty", "<number>", "penalty node: in a paragraph a line-break penalty, between paragraphs a page-break penalty"),
    ("nobreak", "", "\\penalty10000"),
    ("allowbreak", "", "\\penalty0"),
    ("goodbreak", "", "ends the paragraph, then \\penalty-500"),
    ("filbreak", "", "ends the paragraph, then \\vfil\\penalty-200\\vfilneg"),
    ("discretionary", "{pre}{post}{nobreak}", "discretionary break (plain text of each argument)"),
    ("nobreakdash", "- -- ---", "amsmath: the dashes that follow, with no line break after them (\\nobreak)"),
    ("tolerance", "=<number>", "line-breaking parameter, restored at the end of its group"),
    ("pretolerance", "=<number>", "line-breaking parameter, restored at the end of its group"),
    ("looseness", "=<number>", "line-breaking parameter for the next paragraph end"),
    ("widowpenalty", "=<number>", "page-breaking parameter, restored at the end of its group"),
    ("clubpenalty", "=<number>", "page-breaking parameter, restored at the end of its group"),
    ("interlinepenalty", "=<number>", "page-breaking parameter, restored at the end of its group"),
    ("emergencystretch", "=<dimen>", "line-breaking parameter, restored at the end of its group"),
    ("sloppy", "", "\\tolerance 9999, \\emergencystretch 3em, \\hfuzz .5pt"),
    ("fussy", "", "\\tolerance 200, \\emergencystretch 0pt, \\hfuzz .1pt"),
    ("samepage", "", "\\interlinepenalty 10000 for the rest of the group"),
    ("raggedbottom", "", "pages keep their natural height"),
    ("flushbottom", "", "pages are stretched to the text height"),
    ("enlargethispage", "*{dimension}", "the current page's text height grows by the dimension (* also shrinks its glue); pt/cm/.../\\baselineskip multiples"),
    ("hyphenation", "{words}", "hyphenation exceptions: the hyphens mark each word's only break points"),
    ("vfill", "", "vertical glue filling the rest of the page"),
    ("columnbreak", "[n]", "multicol: ends the current column of multicols (priority n, default 4)"),
    ("newcolumn", "", "multicol: ends the current column of multicols, filling it"),
    ("raggedcolumns", "", "multicol: columns keep their natural height"),
    ("flushcolumns", "", "multicol: columns are stretched to one height (the default)"),
    ("thispagestyle", "{style}", "accepted; no headers or footers are rendered"),
    ("pagenumbering", "{style}", "accepted; no page numbers are rendered"),
    ("centering", "", "centres the following paragraphs"),
    ("Centering", "", "centres the following paragraphs (ragged2e form)"),
    ("raggedright", "", "left-aligned following paragraphs"),
    ("RaggedRight", "", "left-aligned following paragraphs (ragged2e form)"),
    ("raggedleft", "", "right-aligned following paragraphs"),
    ("RaggedLeft", "", "right-aligned following paragraphs (ragged2e form)"),
    ("indent", "", "accepted; the first-line indent is diagnosed, not drawn"),
    ("cite", "[note]{keys}", "numbered citation from thebibliography entries; natbib redefines it as \\citet, or as \\citep when an optional argument follows"),
    ("citet", "[pre][post]{keys}", "natbib textual citation: Name (Year); one optional argument is the post-note"),
    ("citep", "[pre][post]{keys}", "natbib parenthetical citation: (Name, Year); one optional argument is the post-note"),
    ("citealt", "[pre][post]{keys}", "natbib \\citet without the parentheses: Name Year"),
    ("citealp", "[pre][post]{keys}", "natbib \\citep without the parentheses: Name, Year"),
    ("citeauthor", "[pre][post]{keys}", "natbib author list alone; the starred form is the long list"),
    ("citefullauthor", "[pre][post]{keys}", "natbib \\citeauthor*: the long author list"),
    ("citeyear", "[pre][post]{keys}", "natbib year alone"),
    ("citeyearpar", "[pre][post]{keys}", "natbib year in parentheses"),
    ("citenum", "[pre][post]{keys}", "natbib \\bibitem number alone, whatever the citation style"),
    ("citetext", "{text}", "natbib's citation delimiters around arbitrary text"),
    ("Citet", "[pre][post]{keys}", "natbib \\citet with the author list's first letter uppercased"),
    ("Citep", "[pre][post]{keys}", "natbib \\citep with the author list's first letter uppercased"),
    ("Citealt", "[pre][post]{keys}", "natbib \\citealt with the author list's first letter uppercased"),
    ("Citealp", "[pre][post]{keys}", "natbib \\citealp with the author list's first letter uppercased"),
    ("Citeauthor", "[pre][post]{keys}", "natbib \\citeauthor with the author list's first letter uppercased"),
    ("nocite", "{keys}", "accepted no-op; there is no .bib pipeline"),
    ("bibitem", "[label]{key}", "entry of thebibliography; natbib's [Author(Year)] and [Author, Year] labels feed author-year citations"),
    ("bibliography", "{files}", "diagnosed: .bib input is not read"),
    ("bibliographystyle", "{style}", "diagnosed: no effect without .bib support"),
    ("title", "{...}", "title for \\maketitle"),
    ("author", "{...}", "author block for \\maketitle; \\and and \\thanks inside it"),
    ("date", "{...}", "date for \\maketitle; \\today inside it"),
    ("maketitle", "", "article.cls title block"),
    // letter.cls. Every one of these exists only under
    // \documentclass{letter}; in any other class they are diagnosed, exactly
    // as pdflatex's "Undefined control sequence" does.
    ("address", "{lines}", "letter.cls return address (\\\\-separated lines), set by \\opening"),
    ("signature", "{name}", "letter.cls name under the closing; falls back to \\name"),
    ("name", "{name}", "letter.cls \\fromname, used when \\signature is empty"),
    ("location", "{text}", "letter.cls \\fromlocation: recorded; only the firstpage footer would set it"),
    ("telephone", "{number}", "letter.cls \\telephonenum: recorded; only the firstpage footer would set it"),
    ("opening", "{salutation}", "letter.cls: return address and date flush right, the recipient, then the salutation"),
    ("closing", "{text}", "letter.cls: closing and signature at \\longindentation, 6\\parskip apart"),
    ("cc", "{text}", "letter.cls carbon-copy line, labelled 'cc:'"),
    ("encl", "{text}", "letter.cls enclosure line, labelled 'encl:'"),
    ("ps", "", "letter.cls postscript: a paragraph break and nothing else — it takes no argument"),
    ("startbreaks", "", "letter.cls: re-allows page breaks after \\closing; no effect on this layout"),
    ("stopbreaks", "", "letter.cls: forbids page breaks inside the closing; no effect on this layout"),
    ("stopletter", "", "letter.cls hook run at \\end{letter}; empty in the class itself"),
    ("makelabels", "", "letter.cls address-label page: accepted, not produced (no .aux round trip)"),
    ("today", "", "the date carried by the compile request; this compiler never reads the clock"),
    ("newtheorem", "{env}[counter]{name}", "defines a numbered theorem-like environment (amsthm)"),
    ("theoremstyle", "{style}", "selects the amsthm style for following \\newtheorem"),
    ("num", "[options]{number}", "siunitx number: digit groups, decimal marker, exponent, uncertainty, as an upright formula"),
    ("unit", "[options]{units}", "siunitx unit: prefixes, powers, \\per as a power, fraction or solidus; literal m/s"),
    ("si", "[options]{units}", "siunitx v2 name of \\unit"),
    ("qty", "[options]{number}{units}", "siunitx quantity: number, unbreakable thin space, unit"),
    ("SI", "[options]{number}[pre-unit]{units}", "siunitx v2 name of \\qty with an optional pre-unit"),
    ("numlist", "[options]{numbers}", "siunitx list of ;-separated numbers joined by list-separator and \" and \""),
    ("numrange", "[options]{number}{number}", "siunitx range: two numbers joined by range-phrase \" to \""),
    ("qtylist", "[options]{numbers}{units}", "siunitx list of quantities, the unit repeated"),
    ("qtyrange", "[options]{number}{number}{units}", "siunitx range of quantities, the unit repeated"),
    ("SIlist", "[options]{numbers}{units}", "siunitx v2 name of \\qtylist"),
    ("SIrange", "[options]{number}{number}{units}", "siunitx v2 name of \\qtyrange"),
    ("ang", "[options]{degrees;minutes;seconds}", "siunitx angle with degree, minute and second marks"),
    ("sisetup", "{options}", "siunitx settings for the following commands (document-global in this model)"),
    ("DeclareSIUnit", "[options]{\\name}{units}", "defines a siunitx unit macro usable inside \\unit and \\qty"),
];

const SIZE_DECLARATIONS: &[&str] = &[
    "tiny",
    "scriptsize",
    "footnotesize",
    "small",
    "normalsize",
    "large",
    "Large",
    "LARGE",
    "huge",
    "Huge",
];

/// Math `command_atom` arms and list-level switches, grouped by behaviour:
/// (names, arguments, description, renders).
const MATH_STRUCTURES: &[(&[&str], &str, &str, bool)] = &[
    (&["color"], "[model]{expression}", "colours the rest of the math group", true),
    (&["textcolor"], "[model]{expression}{body}", "math body in a colour", true),
    (
        &["num", "numlist"],
        "[options]{number}",
        "siunitx number or ;-separated list inside a formula",
        true,
    ),
    (
        &["unit", "si"],
        "[options]{units}",
        "siunitx unit inside a formula",
        true,
    ),
    (
        &["qty", "numrange"],
        "[options]{number}{units}",
        "siunitx quantity (3mu thin space before the unit) or number range inside a formula",
        true,
    ),
    (
        &["SI"],
        "[options]{number}[pre-unit]{units}",
        "siunitx v2 quantity inside a formula",
        true,
    ),
    (
        &["qtylist", "SIlist"],
        "[options]{numbers}{units}",
        "siunitx list of quantities inside a formula",
        true,
    ),
    (
        &["qtyrange", "SIrange"],
        "[options]{number}{number}{units}",
        "siunitx range of quantities inside a formula",
        true,
    ),
    (
        &["ang"],
        "[options]{angle}",
        "siunitx angle inside a formula",
        true,
    ),
    (
        &["sisetup"],
        "{options}",
        "siunitx settings changed inside a formula",
        true,
    ),
    (
        &["rule"],
        "[raise]{dimension}{dimension}",
        "latex.ltx \\rule box in a formula, em/ex of the text font",
        true,
    ),
    (
        &["frac", "cfrac"],
        "{num}{den}",
        "fraction; \\cfrac lays out as \\frac",
        true,
    ),
    (
        &["dfrac", "tfrac"],
        "{num}{den}",
        "amsmath \\genfrac fraction in display or text style",
        true,
    ),
    (
        &["genfrac"],
        "{left}{right}{thickness}{style}{num}{den}",
        "amsmath generalized fraction: delimiters, pt rule thickness and a 0-3 style",
        true,
    ),
    (
        &["phantom", "hphantom", "vphantom"],
        "{x}",
        "empty box with the width and/or height and depth of the argument",
        true,
    ),
    (
        &["xrightarrow", "xleftarrow", "xleftrightarrow"],
        "[below]{above}",
        "amsmath/mathtools extensible arrow stretched to its labels (\\ext@arrow)",
        true,
    ),
    (
        &["substack"],
        "{a \\\\ b}",
        "amsmath centred script-style rows for limits",
        true,
    ),
    (
        &["sqrt"],
        "[index]{x}",
        "radical with optional raised index",
        true,
    ),
    (
        &["binom", "dbinom", "tbinom"],
        "{n}{k}",
        "amsmath binomial: zero-thickness \\genfrac in parentheses; d/t forms force the style",
        true,
    ),
    (
        &["choose", "over"],
        "",
        "TeX infix binomial and fraction inside a group",
        true,
    ),
    (
        &["overset", "stackrel", "underset"],
        "{script}{base}",
        "script-size list centred above or below a base",
        true,
    ),
    (
        &["sideset"],
        "{left scripts}{right scripts}{operator}",
        "scripts on both sides of a large operator, set in \\displaystyle (\\mathop)",
        true,
    ),
    (
        &["operatorname", "operatornamewithlimits"],
        "{name}",
        "upright named operator (\\mathop); starred and withlimits forms take limits",
        true,
    ),
    (
        &["colon"],
        "",
        "function-arrow colon: punctuation (0mu/3mu) as the kernel declares it, amsmath's 2mu/6mu when amsmath is loaded",
        true,
    ),
    (
        &["eqqcolon"],
        "",
        "mathtools =: (reverse of \\coloneqq) as a relation; needs mathtools",
        true,
    ),
    (
        &["Coloneqq", "Eqqcolon"],
        "",
        "mathtools ::= and =:: (each three real glyphs) as one relation; needs mathtools",
        true,
    ),
    (
        &["vcentcolon"],
        "",
        "mathtools vertically centred colon: the same glyph as \\colon as a relation; needs mathtools",
        true,
    ),
    (
        &["dblcolon"],
        "",
        "mathtools double vertically centred colon (two \\vcentcolon) as one relation; needs mathtools",
        true,
    ),
    (&["bmod", "mod"], "", "upright mod", true),
    (&["pmod"], "{n}", "parenthesised (mod n)", true),
    (
        &["mathbb"],
        "{A-Z}",
        "double-struck capitals from Latin Modern Math; other arguments are diagnosed",
        true,
    ),
    (
        &["mathfrak"],
        "{letters}",
        "Euler Fraktur letters as Unicode mathematical fraktur; digits and other characters unchanged",
        true,
    ),
    (
        &["mathcal"],
        "{A-Z}",
        "script capitals from New Computer Modern Math at cmsy10 metrics; other arguments are diagnosed",
        true,
    ),
    (
        &["varnothing"],
        "",
        "empty set at msbm10's 0.7778em advance (\\emptyset's glyph)",
        true,
    ),
    (
        &["iff", "implies", "impliedby"],
        "",
        "long double arrow between thick (5mu) spaces",
        true,
    ),
    (
        &["bot", "bigtriangleup"],
        "",
        "shared symbol glyph with its own atom class (Ord / Bin)",
        true,
    ),
    (
        &[
            "mathbin",
            "mathrel",
            "mathord",
            "mathop",
            "mathopen",
            "mathclose",
            "mathpunct",
        ],
        "{math}",
        "argument boxed as one atom of the forced class",
        true,
    ),
    (
        &["mathbf", "textbf"],
        "{text}",
        "literal text in Times-Bold",
        true,
    ),
    (
        &["mathit", "mathsf", "mathtt"],
        "{...}",
        "letters and digits of a plain argument as Unicode mathematical italic, sans-serif or monospace; any other argument stays in the current math face",
        true,
    ),
    (
        &[
            "mathrm",
            "mathnormal",
            "boldsymbol",
            "bm",
            "mbox",
            "hbox",
            "textrm",
            "textit",
            "textnormal",
        ],
        "{...}",
        "keeps its argument in the current math face (no distinct face yet)",
        true,
    ),
    (&["text"], "{text}", "literal text in math", true),
    (
        &["boxed", "overline", "underline"],
        "{...}",
        "real rule around, over or under the body",
        true,
    ),
    (
        &["overbrace", "underbrace"],
        "{body}",
        "cmex brace pieces with rule fills over or under a display-style body; scripts are limits",
        true,
    ),
    (
        &[
            "overrightarrow",
            "overleftarrow",
            "overleftrightarrow",
            "underrightarrow",
            "underleftarrow",
            "underleftrightarrow",
        ],
        "{body}",
        "amsmath \\arrowfill@ as wide as the body, over or under it",
        true,
    ),
    (
        &["dashrightarrow", "dasharrow", "dashleftarrow"],
        "",
        "amsfonts dashed arrow: two msam \\dabar@ pieces and a head in one relation",
        true,
    ),
    (&["Bbb"], "{A-Z}", "obsolete amsfonts alias of \\mathbb", true),
    (&["bold"], "{text}", "obsolete amsfonts alias of \\mathbf", true),
    (
        &[
            "hat", "bar", "vec", "tilde", "dot", "ddot", "acute", "grave",
        ],
        "{body}",
        "base-14 accent glyph centred over the body",
        true,
    ),
    (
        &["widehat", "widetilde"],
        "{body}",
        "cmex successor-chain accent grown to the body (msbm extra-wide form past 2em with amsfonts)",
        true,
    ),
    (
        &["check", "breve"],
        "{body}",
        "parsed, but no base-14 glyph exists: diagnosed and typeset without a mark",
        false,
    ),
    (
        &[
            "left", "right", "big", "Big", "bigg", "Bigg", "bigl", "bigr", "Bigl", "Bigr", "biggl",
            "biggr", "Biggl", "Biggr", "bigm", "Bigm", "biggm", "Biggm",
        ],
        "",
        "consumes the following delimiter, kept at ordinary size",
        true,
    ),
    (
        &["dots", "ldots", "dotsc", "dotso"],
        "",
        "three periods",
        true,
    ),
    (
        &["cdots", "dotsb", "dotsm", "dotsi"],
        "",
        "three math-axis dots",
        true,
    ),
    (&["iint", "iiint"], "", "repeated integral glyph", true),
    (&["lbrace", "rbrace"], "", "brace glyph", true),
    (&["quad", "qquad"], "", "1em/2em math space", true),
    (
        &[
            "displaystyle",
            "textstyle",
            "scriptstyle",
            "scriptscriptstyle",
        ],
        "",
        "accepted without changing size",
        true,
    ),
    (
        &["limits", "nolimits"],
        "",
        "accepted without changing script placement",
        true,
    ),
    (
        &["nonumber", "notag", "middle"],
        "",
        "accepted without effect",
        true,
    ),
    (
        &["tag"],
        "{label}",
        "(label) two quads after the display; starred form without parentheses",
        true,
    ),
    (&["begin"], "{env}", "opens a math grid environment", true),
];

/// Control symbols the lexer or math reader turns into something other than
/// a literal character: (name, mode, description).
const CONTROL_SYMBOLS: &[(&str, Mode, &str)] = &[
    (
        "\\",
        Mode::Text,
        "line break; an optional [length] is consumed",
    ),
    (
        "-",
        Mode::Text,
        "discretionary hyphen: a break point, invisible unless the line breaks there",
    ),
    (",", Mode::Text, "text kern .16667em (\\thinspace)"),
    ("!", Mode::Text, "text kern -.16667em (\\negthinspace)"),
    (":", Mode::Text, "text kern .2222em (\\medspace)"),
    (">", Mode::Text, "text kern .2222em (\\medspace)"),
    (";", Mode::Text, "text kern .2777em (\\thickspace)"),
    (",", Mode::Math, "thin space (3mu)"),
    (":", Mode::Math, "medium space (4mu)"),
    (">", Mode::Math, "medium space (4mu)"),
    (";", Mode::Math, "thick space (5mu)"),
    (" ", Mode::Math, "control space (6mu)"),
    ("!", Mode::Math, "negative thin space (-3mu)"),
    ("|", Mode::Math, "double vertical bar"),
];

/// Text-level environments with a `parser::Parser::environment` arm.
const TEXT_ENVIRONMENTS: &[(&str, &str)] = &[
    (
        "document",
        "the typeset body; preamble content is not typeset",
    ),
    (
        "letter",
        "letter.cls: one letter to {recipient\\\\address}, starting a new page",
    ),
    ("equation", "numbered display"),
    ("equation*", "unnumbered display"),
    ("displaymath", "unnumbered display"),
    ("gather", "centred rows, each numbered"),
    ("gather*", "centred rows"),
    ("align", "rows aligned at &, each numbered"),
    ("align*", "rows aligned at &"),
    (
        "alignat",
        "rows aligned at &, each numbered; the column count is consumed",
    ),
    (
        "alignat*",
        "rows aligned at &; the column count is consumed",
    ),
    ("flalign", "rows aligned at &, each numbered"),
    ("flalign*", "rows aligned at &"),
    (
        "multline",
        "multi-line display; only the last line is numbered",
    ),
    ("multline*", "multi-line display"),
    (
        "subequations",
        "amsmath: displays inside number as the parent number plus a, b, ...; a \\label right after \\begin gets the parent number",
    ),
    ("figure", "numbered captions; no floating"),
    ("center", "centred paragraphs"),
    ("flushleft", "left-aligned paragraphs"),
    ("flushright", "right-aligned paragraphs"),
    ("quote", "indented paragraphs"),
    ("quotation", "indented paragraphs"),
    ("sloppypar", "a paragraph set with \\sloppy"),
    ("samepage", "\\samepage for the body"),
    ("verse", "indented lines; each \\\\ ends a line"),
    ("itemize", "bulleted list; article labels per depth, \\item[label]"),
    (
        "enumerate",
        "numbered list; article labels per depth, enumitem label/label*/shortlabels, start and resume",
    ),
    ("description", "list of bold \\item[term] labels"),
    ("tabular", "table with l/c/r/p columns, rules and multicolumn; with array also >{} <{} !{} m b w and \\extrarowheight; with siunitx S[options] number and s unit columns, centred rather than decimal-aligned"),
    ("tabular*", "table of a given width"),
    ("verbatim", "literal monospaced lines"),
    ("verbatim*", "literal monospaced lines with visible spaces"),
    ("lstlisting", "literal monospaced lines (basic listings)"),
    ("proof", "amsthm proof with a closing square"),
    (
        "thebibliography",
        "References section with numbered \\bibitem entries",
    ),
    (
        "multicols",
        "multicol {n}[preface][premulticols]: balanced columns, laid out by the render pipeline",
    ),
    (
        "multicols*",
        "multicol {n}[preface][premulticols]: unbalanced columns, laid out by the render pipeline",
    ),
];

/// Packages `parser::package_matches_layout` accepts without a warning.
const PACKAGES: &[(&str, &str, &str)] = &[
    (
        "inputenc",
        "utf8",
        "source text is already decoded as UTF-8",
    ),
    ("fontenc", "T1", "text glyphs are mapped from Unicode"),
    (
        "hyperref",
        "colorlinks, hidelinks, bookmarks, bookmarksopen, bookmarksnumbered, linktoc, breaklinks, unicode, pageanchor, hyperfootnotes, pdfstartview, pdfpagemode",
        "loading hyperref moves no glyph (measured against pdflatex, TeX Live 2025: the same document with and without it is 1062 words on 4 pages, 0 moved), and the link-colour, border, outline, viewer and pdf* metadata keys are accepted with it; \\url, \\href and \\nolinkurl are typeset, while the PDF links, bookmarks and link colours still missing are reported once by their own diagnostic; backref and pagebackref add bibliography text and keep warning",
    ),
    (
        "cleveref",
        "capitalise, noabbrev",
        "named cross-references with compressed ranges; unknown package options are silently ignored",
    ),
    ("color", "dvipsnames, usenames", "color.sty colours with pdfTeX's exact operator values"),
    (
        "xcolor",
        "natural, rgb, cmy, cmyk, gray, dvipsnames, svgnames, x11names, table",
        "xcolor 3.02 definitions, expressions and target models with pdfTeX's exact operator values; hsb models, colour series and table colours are diagnosed",
    ),
    (
        "amsmath",
        "centertags, sumlimits, nointlimits, namelimits, reqno",
        "the align, gather, multline, split, aligned, gathered, cases and matrix families; \\dfrac, \\tfrac, \\binom, \\genfrac, \\cfrac, \\substack, \\operatorname, \\DeclareMathOperator, \\boxed, \\phantom, \\overset/\\underset, the extensible arrows, \\text in math, \\tag/\\notag and \\eqref, \\sideset, with \\lim-family, \\sum and \\prod display limits and amsmath's wider \\colon. Its defaults are the accepted options; leqno, fleqn, tbtags, nosumlimits, intlimits and nonamelimits move real output and keep warning. \\shoveleft, \\smash, \\mspace, \\hdotsfor and \\varinjlim are each diagnosed where they are used",
    ),
    (
        "amssymb",
        "",
        "the full AMSa/AMSb (msam/msbm) inventory of amssymb.sty -- 203 names base LaTeX2e leaves undefined (\\square, \\nleq, ...) -- plus everything amsfonts declares; loading the package is what makes the names exist, and a name whose file was not loaded is diagnosed",
    ),
    (
        "amsfonts",
        "",
        "amsfonts.sty's 22-name symbol subset (\\ulcorner, \\square, \\yen, the dashed arrows) and the \\mathbb and \\mathfrak alphabets; the rest of amssymb stays undefined without \\usepackage{amssymb}",
    ),
    (
        "amsthm",
        "",
        "\\newtheorem, \\theoremstyle and the proof environment",
    ),
    (
        "array",
        "",
        "tabular >{} <{} !{} m b w columns, \\newcolumntype and \\extrarowheight",
    ),
    (
        "booktabs",
        "",
        "\\toprule, \\midrule, \\bottomrule, \\cmidrule(trim), \\addlinespace, \\specialrule, \\morecmidrules",
    ),
    (
        "longtable",
        "",
        "the page-breaking longtable environment: \\endfirsthead, \\endhead, \\endfoot, \\endlastfoot, \\caption, \\kill, \\\\*",
    ),
    (
        "multirow",
        "",
        "\\multirow[vpos]{rows}[bigstruts]{width}[vmove]{text} in table entries",
    ),
    (
        "colortbl",
        "",
        "\\rowcolor, \\cellcolor, >{\\columncolor}, \\arrayrulecolor, \\doublerulesepcolor",
    ),
    (
        "enumitem",
        "shortlabels",
        "list keys (label, start, resume, seps, margins) parsed as options; \\setlist",
    ),
    (
        "geometry",
        "letterpaper, margin=1in",
        "matches the fixed US Letter page with 1in margins",
    ),
    (
        "siunitx",
        "any \\sisetup keys",
        "v3 \\num, \\unit, \\qty, lists, ranges, \\ang, \\sisetup and \\DeclareSIUnit; unmodelled keys are diagnosed",
    ),
    (
        "multicol",
        "",
        "multicols and multicols* with preface, \\columnbreak, \\raggedcolumns (columns set by the render pipeline)",
    ),
    (
        "natbib",
        "numbers, authoryear, round, square, angle, curly, comma, semicolon, colon, nobibstyle, bibstyle, sectionbib, longnamesfirst, nonamebreak",
        "\\citet/\\citep/\\citealt/\\citealp/\\citeauthor/\\citeyear/\\citeyearpar/\\citenum/\\citetext and the \\cite it redefines, with [Author(Year)] \\bibitem labels; sort, compress, super and openbib are diagnosed",
    ),
    (
        "ulem",
        "normalem",
        "\\uline: 0.4pt rule under the argument (single-line); \\sout: 0.4pt strike at 0.55ex; \\emph is not redefined",
    ),
];

/// The vendored coverage denominator.
pub const CANONICAL_TSV: &str = include_str!("../supported/canonical-latex.tsv");

/// Canonical sets, in report order.
pub const CANONICAL_SETS: &[&str] = &[
    "kernel", "amsmath", "amssymb", "enumitem", "geometry", "graphicx", "hyperref", "tikz", "xcolor",
    "siunitx",
];

fn text_description(name: &str) -> String {
    if let Some((_, command)) = crate::text_builtins::TEXT_SYMBOLS
        .iter()
        .find(|(n, _)| *n == name)
    {
        let glyph = |enc| match crate::text_builtins::text_symbol(name, enc) {
            Some(crate::text_builtins::SymbolOutcome::Char(c)) => c.to_string(),
            Some(crate::text_builtins::SymbolOutcome::Text(t)) => t,
            _ => "unavailable".to_string(),
        };
        use flashtex_tex_text_encoding::encoding::Encoding;
        return format!(
            "text symbol {command}: OT1 {}, T1 {} (tex-text-encoding; unavailable is a LaTeX error)",
            glyph(Encoding::OT1),
            glyph(Encoding::T1)
        );
    }
    text_description_static(name).to_string()
}

fn text_description_static(name: &str) -> &'static str {
    TEXT_COMMANDS
        .iter()
        .find(|(n, ..)| *n == name)
        .map(|(_, _, d)| *d)
        .unwrap_or("")
}

fn text_arguments(name: &str) -> &'static str {
    TEXT_COMMANDS
        .iter()
        .find(|(n, ..)| *n == name)
        .map(|(_, a, _)| *a)
        .unwrap_or("")
}

pub fn inventory() -> Inventory {
    let mut commands = Vec::new();
    for &name in parser::BUILT_INS.iter().chain(TEXT_EXTRA_ARMS) {
        if TEXT_DIAGNOSTIC_ONLY.contains(&name) {
            continue;
        }
        let origin = if SIZE_DECLARATIONS.contains(&name) {
            Origin::TextSize
        } else if parser::style_command(name) || parser::style_declaration(name) {
            Origin::TextStyle
        } else {
            Origin::TextDispatch
        };
        commands.push(Command {
            name,
            mode: Mode::Text,
            origin,
            arguments: text_arguments(name),
            description: text_description(name),
            glyph: None,
            renders: true,
        });
    }
    for &(name, arguments, description) in EXPANSION_COMMANDS {
        commands.push(Command {
            name,
            mode: Mode::Text,
            origin: Origin::Expansion,
            arguments,
            description: description.to_string(),
            glyph: None,
            renders: true,
        });
    }
    for &(name, mode, description) in CONTROL_SYMBOLS {
        commands.push(Command {
            name,
            mode,
            origin: Origin::ControlSymbol,
            arguments: "",
            description: description.to_string(),
            glyph: None,
            renders: true,
        });
    }
    for &(names, arguments, description, renders) in MATH_STRUCTURES {
        for &name in names {
            commands.push(Command {
                name,
                mode: Mode::Math,
                origin: Origin::MathStructure,
                arguments,
                description: description.to_string(),
                glyph: None,
                renders,
            });
        }
    }
    for &(name, glyph) in math::COMMAND_GLYPHS {
        // A `command_atom` arm runs before the glyph table (`\varnothing`
        // keeps `∅` but forces msbm10's advance), so the structure entry
        // above already describes it.
        if MATH_STRUCTURES
            .iter()
            .any(|(names, ..)| names.contains(&name))
            || crate::amssymb::by_name(name).is_some()
        {
            continue;
        }
        commands.push(Command {
            name,
            mode: Mode::Math,
            origin: Origin::MathSymbol,
            arguments: "",
            description: format!("symbol {glyph}"),
            glyph: Some(glyph),
            renders: true,
        });
    }
    // amssymb/amsfonts symbols (`crate::amssymb`), which take precedence over
    // the glyph rows above for the names both list.
    for name in crate::amssymb::command_names() {
        if MATH_STRUCTURES.iter().any(|(names, ..)| names.contains(&name)) {
            continue;
        }
        let ams = crate::amssymb::by_name(name).expect("a listed amssymb command");
        let font = match ams.font {
            crate::amssymb::SymbolFont::Msam => "msam",
            crate::amssymb::SymbolFont::Msbm => "msbm",
        };
        let class = format!("{:?}", ams.class).to_lowercase();
        // Which `\usepackage` the document has to load: base LaTeX2e defines
        // none of these names, and `math::command_atom` diagnoses the command
        // when its package is absent, so the inventory has to say so.
        let package = match ams.provider {
            crate::amssymb::Provider::Amsfonts => "amsfonts",
            crate::amssymb::Provider::Amssymb => "amssymb",
        };
        commands.push(Command {
            name,
            mode: Mode::Math,
            origin: Origin::MathSymbol,
            arguments: "",
            description: format!(
                "symbol {} (\\math{class}, {font} \"{:02X}; needs {package})",
                ams.text, ams.slot
            ),
            glyph: Some(ams.text),
            renders: true,
        });
    }
    for &name in math::OPERATOR_NAMES {
        commands.push(Command {
            name,
            mode: Mode::Math,
            origin: Origin::MathOperator,
            arguments: "",
            description: "upright operator name".to_string(),
            glyph: None,
            renders: true,
        });
    }

    let mut environments: Vec<Environment> = TEXT_ENVIRONMENTS
        .iter()
        .map(|&(name, description)| Environment {
            name,
            mode: Mode::Text,
            description: description.to_string(),
        })
        .collect();
    for &(name, align, left, right) in math::GRID_ENVIRONMENTS {
        let fences = match (left, right) {
            ("", "") => String::new(),
            (l, "") => format!(" with a left {l}"),
            (l, r) => format!(" in {l} {r}"),
        };
        let align = match align {
            'l' => "left-aligned",
            'r' => "right-aligned",
            _ => "centred",
        };
        environments.push(Environment {
            name,
            mode: Mode::Math,
            description: format!("math grid, {align} cells{fences}"),
        });
    }

    let packages = PACKAGES
        .iter()
        .map(|&(name, options, description)| Package {
            name,
            options,
            description,
        })
        .collect();

    Inventory {
        commands,
        environments,
        packages,
    }
}

/// One canonical set and kind with the supported names found in it.
#[derive(Clone, Debug, PartialEq)]
pub struct CoverageRow {
    pub set: &'static str,
    pub kind: &'static str,
    pub canonical: Vec<&'static str>,
    pub supported: Vec<&'static str>,
}

impl CoverageRow {
    pub fn percent(&self) -> f64 {
        percent(self.supported.len(), self.canonical.len())
    }
}

fn percent(part: usize, whole: usize) -> f64 {
    if whole == 0 {
        0.0
    } else {
        (1000.0 * part as f64 / whole as f64).round() / 10.0
    }
}

/// `(set, kind, name)` rows of the canonical list.
pub fn canonical_entries() -> Vec<(&'static str, &'static str, &'static str)> {
    CANONICAL_TSV
        .lines()
        .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        .filter_map(|line| {
            let mut fields = line.split('\t');
            Some((fields.next()?, fields.next()?, fields.next()?))
        })
        .collect()
}

/// `# Engine:` and `# Source ...:` header lines, without the `# `.
pub fn canonical_sources() -> Vec<&'static str> {
    CANONICAL_TSV
        .lines()
        .filter_map(|line| line.strip_prefix("# "))
        .filter(|line| line.starts_with("Engine:") || line.starts_with("Source "))
        .collect()
}

pub fn coverage(inventory: &Inventory) -> Vec<CoverageRow> {
    let entries = canonical_entries();
    let mut rows = Vec::new();
    for &set in CANONICAL_SETS {
        for kind in ["command", "environment"] {
            let canonical: Vec<&'static str> = entries
                .iter()
                .filter(|(s, k, _)| *s == set && *k == kind)
                .map(|(_, _, name)| *name)
                .collect();
            if canonical.is_empty() {
                continue;
            }
            let supported = canonical
                .iter()
                .copied()
                .filter(|name| {
                    if kind == "command" {
                        inventory
                            .commands
                            .iter()
                            .any(|command| command.renders && command.name == *name)
                    } else {
                        inventory.environments.iter().any(|env| env.name == *name)
                    }
                })
                .collect();
            rows.push(CoverageRow {
                set,
                kind,
                canonical,
                supported,
            });
        }
    }
    rows
}

fn totals(rows: &[CoverageRow]) -> (usize, usize) {
    rows.iter().fold((0, 0), |(s, c), row| {
        (s + row.supported.len(), c + row.canonical.len())
    })
}

// ---- rendering ---------------------------------------------------------

fn json_str(s: &str) -> String {
    let mut out = String::new();
    write_string_into(s, &mut out);
    out
}

/// Pretty, one-entry-per-line JSON (stable for review diffs).
pub fn render_json(inventory: &Inventory) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str("  \"schema\": \"flashtex-supported-latex/1\",\n");
    out.push_str("  \"generator\": \"flashtex-compiler --supported json\",\n");
    out.push_str(&format!(
        "  \"compiler_version\": {},\n",
        json_str(env!("CARGO_PKG_VERSION"))
    ));
    out.push_str(
        "  \"unsupported_behaviour\": \"any other command produces an explicit 'not supported' diagnostic naming it\",\n",
    );
    out.push_str("  \"commands\": [\n");
    let lines: Vec<String> = inventory
        .commands
        .iter()
        .map(|c| {
            let mut line = format!(
                "    {{\"name\": {}, \"mode\": \"{}\", \"origin\": \"{}\", \"arguments\": {}, \"description\": {}, \"renders\": {}",
                json_str(c.name),
                c.mode.as_str(),
                c.origin.as_str(),
                json_str(c.arguments),
                json_str(&c.description),
                c.renders
            );
            if let Some(glyph) = c.glyph {
                line.push_str(&format!(", \"glyph\": {}", json_str(glyph)));
            }
            line.push('}');
            line
        })
        .collect();
    out.push_str(&lines.join(",\n"));
    out.push_str("\n  ],\n  \"environments\": [\n");
    let lines: Vec<String> = inventory
        .environments
        .iter()
        .map(|e| {
            format!(
                "    {{\"name\": {}, \"mode\": \"{}\", \"description\": {}}}",
                json_str(e.name),
                e.mode.as_str(),
                json_str(&e.description)
            )
        })
        .collect();
    out.push_str(&lines.join(",\n"));
    out.push_str("\n  ],\n  \"packages\": [\n");
    let lines: Vec<String> = inventory
        .packages
        .iter()
        .map(|p| {
            format!(
                "    {{\"name\": {}, \"silent_options\": {}, \"description\": {}}}",
                json_str(p.name),
                json_str(p.options),
                json_str(p.description)
            )
        })
        .collect();
    out.push_str(&lines.join(",\n"));
    out.push_str("\n  ],\n  \"coverage\": {\n    \"sources\": [\n");
    let lines: Vec<String> = canonical_sources()
        .iter()
        .map(|s| format!("      {}", json_str(s)))
        .collect();
    out.push_str(&lines.join(",\n"));
    out.push_str("\n    ],\n    \"rows\": [\n");
    let rows = coverage(inventory);
    let lines: Vec<String> = rows
        .iter()
        .map(|row| {
            let mut pct = String::new();
            write_number_into(row.percent(), &mut pct);
            format!(
                "      {{\"set\": \"{}\", \"kind\": \"{}\", \"canonical\": {}, \"supported\": {}, \"percent\": {}}}",
                row.set,
                row.kind,
                row.canonical.len(),
                row.supported.len(),
                pct
            )
        })
        .collect();
    out.push_str(&lines.join(",\n"));
    let (supported, canonical) = totals(&rows);
    let mut pct = String::new();
    write_number_into(percent(supported, canonical), &mut pct);
    out.push_str(&format!(
        "\n    ],\n    \"total\": {{\"canonical\": {canonical}, \"supported\": {supported}, \"percent\": {pct}}}\n  }}\n}}\n"
    ));
    out
}

fn md_code(name: &str) -> String {
    format!("`\\{}`", name.replace('|', "\\|"))
}

fn md_cell(text: &str) -> String {
    text.replace('|', "\\|")
}

/// The coverage table alone, for README benchmark sections.
pub fn render_coverage_markdown(inventory: &Inventory) -> String {
    let rows = coverage(inventory);
    let mut out = String::new();
    out.push_str("| Canonical set | Commands supported | Environments supported |\n");
    out.push_str("| --- | ---: | ---: |\n");
    for &set in CANONICAL_SETS {
        let cell = |kind: &str| match rows.iter().find(|r| r.set == set && r.kind == kind) {
            Some(row) => format!(
                "{}/{} ({:.1}%)",
                row.supported.len(),
                row.canonical.len(),
                row.percent()
            ),
            None => "none defined".to_string(),
        };
        out.push_str(&format!(
            "| {} | {} | {} |\n",
            set,
            cell("command"),
            cell("environment")
        ));
    }
    let (supported, canonical) = totals(&rows);
    out.push_str(&format!(
        "| **total** | **{}/{} ({:.1}%)** | |\n",
        supported,
        canonical,
        percent(supported, canonical)
    ));
    out.push_str(
        "\nGenerated by `flashtex-compiler --supported coverage` against \
         `crates/compiler/supported/canonical-latex.tsv` (LaTeX2e reference-manual index and \
         package sources, each name confirmed by pdfLaTeX; TeX Live 2026). The total row counts \
         commands and environments together. Supported means handled without an unsupported \
         diagnostic, not typographic parity.\n",
    );
    // #254 added this caveat to `supported/coverage.md` by hand. That file is
    // generated, so the note broke `generated_artifacts_are_current` and the
    // next regeneration would have silently deleted it. It belongs here, where
    // regeneration reproduces it.
    out.push_str(
        "\n**The denominator excludes math-mode symbol commands entirely.** `canonical-latex.tsv`'s candidates are `@findex`/`@EnvIndex` entries from the LaTeX2e reference manual plus each listed package's own source files (see `crates/compiler/scripts/canonical_latex.py`'s header); math symbols such as `\\alpha` and `\\odot` are neither in that manual's index nor in any of the nine package source lists, so they never become candidates and are absent from the table. The compiler tracks math-command support separately (`crates/compiler/src/math.rs`'s `COMMAND_GLYPHS`/`OPERATOR_NAMES`, `crates/compiler/src/supported.rs`'s `Origin::MathSymbol`/`MathOperator`/`MathStructure`; the full list is in `docs/user/compiler.md`'s math tables), but `--supported coverage` does not count them.\n",
    );
    out
}

pub const DOC_BEGIN: &str =
    "<!-- BEGIN GENERATED supported-latex: `flashtex-compiler --supported markdown`; do not edit by hand -->";
pub const DOC_END: &str = "<!-- END GENERATED supported-latex -->";

/// The "Supported LaTeX" section of `docs/user/compiler.md`, markers included.
pub fn render_markdown(inventory: &Inventory) -> String {
    let mut out = String::new();
    out.push_str(DOC_BEGIN);
    out.push_str("\n## Supported LaTeX\n\n");
    let text = inventory
        .commands
        .iter()
        .filter(|c| c.mode == Mode::Text)
        .count();
    let math = inventory
        .commands
        .iter()
        .filter(|c| c.mode == Mode::Math)
        .count();
    out.push_str(&format!(
        "This compiler implements a finite LaTeX subset: {} text-mode and {} math-mode command \
         entries, {} environments and {} layout-neutral packages. Every other command produces \
         an explicit \"not supported\" diagnostic naming it, and every other environment or \
         package a warning; nothing is dropped silently. Descriptions note approximations. \
         Outstanding features with reproductions are in `crates/compiler/UNSUPPORTED.md`.\n\n",
        text,
        math,
        inventory.environments.len(),
        inventory.packages.len()
    ));
    out.push_str(
        "Regenerate with `crates/compiler/scripts/render_supported_latex.sh`; \
         `cargo test --test supported_latex` fails when this section is stale.\n\n",
    );

    out.push_str("### Coverage\n\n");
    out.push_str(&render_coverage_markdown(inventory));
    out.push_str("\nCanonical sources:\n\n");
    for source in canonical_sources() {
        out.push_str(&format!("- {}\n", source));
    }

    let table = |out: &mut String, title: &str, filter: &dyn Fn(&Command) -> bool| {
        out.push_str(&format!(
            "\n### {title}\n\n| Command | Arguments | Behaviour |\n| --- | --- | --- |\n"
        ));
        for c in inventory.commands.iter().filter(|c| filter(c)) {
            let arguments = if c.arguments.is_empty() {
                String::new()
            } else {
                format!("`{}`", md_cell(c.arguments))
            };
            out.push_str(&format!(
                "| {} | {} | {} |\n",
                md_code(c.name),
                arguments,
                md_cell(&c.description)
            ));
        }
    };
    table(&mut out, "Text commands", &|c| {
        c.mode == Mode::Text && c.origin != Origin::Expansion
    });
    table(&mut out, "Commands run by the expansion pass", &|c| {
        c.origin == Origin::Expansion
    });
    table(&mut out, "Math structures", &|c| {
        c.mode == Mode::Math && matches!(c.origin, Origin::MathStructure | Origin::ControlSymbol)
    });

    out.push_str("\n### Math symbols\n\n");
    let symbols: Vec<String> = inventory
        .commands
        .iter()
        .filter(|c| c.origin == Origin::MathSymbol)
        .map(|c| format!("{} {}", md_code(c.name), c.glyph.unwrap_or("")))
        .collect();
    out.push_str(&symbols.join(", "));
    out.push_str(".\n\n### Operator names\n\nTypeset as upright words: ");
    let operators: Vec<String> = inventory
        .commands
        .iter()
        .filter(|c| c.origin == Origin::MathOperator)
        .map(|c| md_code(c.name))
        .collect();
    out.push_str(&operators.join(", "));
    out.push_str(
        ".\n\n### Environments\n\n| Environment | Mode | Behaviour |\n| --- | --- | --- |\n",
    );
    for e in &inventory.environments {
        out.push_str(&format!(
            "| `{}` | {} | {} |\n",
            e.name,
            e.mode.as_str(),
            md_cell(&e.description)
        ));
    }
    out.push_str("\n### Packages loaded without a warning\n\n| Package | Options | Why it is silent |\n| --- | --- | --- |\n");
    for p in &inventory.packages {
        out.push_str(&format!(
            "| `{}` | `{}` | {} |\n",
            p.name,
            p.options,
            md_cell(p.description)
        ));
    }
    out.push_str(
        "\nAny other package, or these packages with other options, is recorded and reported \
         as recognised but not implemented.\n",
    );
    out.push_str(DOC_END);
    out.push('\n');
    out
}
