#!/usr/bin/env bash
# Copies the compiler's machine-readable command inventory
# (crates/compiler/supported/supported-latex.json, schema
# flashtex-supported-latex/1, regenerated by `flashtex-compiler --supported
# json` and drift-gated by crates/compiler/tests/supported_latex.rs) into the
# Mac app's SwiftPM resources, where Completion.Vocabulary decodes it. The
# editor's completion vocabulary is generated from this file, never written
# by hand, so the two copies must be byte-identical.
#
# NOTE: crates/compiler/scripts/render_supported_latex.sh invokes this script
# automatically after regenerating the inventory, so a re-render never leaves
# the bundled copy stale; run this script directly only for a sync without a
# re-render (its --check mode is what CI and make-app.sh use).
#
# Usage: apps/mac/scripts/sync-supported-latex.sh [--check] [--root <repo>]
#   --check  do not copy; exit 1 when the bundled copy differs (CI, make-app.sh)
#   --root   repository checkout holding crates/ (default: this repository)
#
# CompletionTests.testBundledInventoryMatchesTheCompiler makes the same
# comparison (sha256) whenever the repository checkout is available.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAC_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT="$(cd "$MAC_DIR/../.." && pwd)"
CHECK=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK=1; shift ;;
    --root) ROOT="$(cd "${2:?--root needs a path}" && pwd)"; shift 2 ;;
    -h|--help) sed -n '2,15p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "sync-supported-latex.sh: unknown argument: $1" >&2; exit 2 ;;
  esac
done

SOURCE="$ROOT/crates/compiler/supported/supported-latex.json"
TARGET="$MAC_DIR/Sources/FlashTeXMac/Resources/supported-latex.json"

[[ -f "$SOURCE" ]] || { echo "sync-supported-latex.sh: missing $SOURCE (regenerate with: cargo run --manifest-path crates/compiler/Cargo.toml -- --supported json)" >&2; exit 1; }
grep -q '"schema": "flashtex-supported-latex/1"' "$SOURCE" || { echo "sync-supported-latex.sh: $SOURCE is not schema flashtex-supported-latex/1" >&2; exit 1; }

if cmp -s "$SOURCE" "$TARGET"; then
  echo "sync-supported-latex.sh: bundled copy is current ($(shasum -a 256 "$TARGET" | cut -c1-12))"
  exit 0
fi
if [[ "$CHECK" == 1 ]]; then
  echo "sync-supported-latex.sh: $TARGET differs from $SOURCE; run apps/mac/scripts/sync-supported-latex.sh and commit the result" >&2
  exit 1
fi
mkdir -p "$(dirname "$TARGET")"
cp "$SOURCE" "$TARGET"
echo "sync-supported-latex.sh: copied $SOURCE -> $TARGET ($(shasum -a 256 "$TARGET" | cut -c1-12))"
