#!/usr/bin/env python3
"""Coverage map for the lockstep corpus: which tex.web / pdftex.web sections
and which primitives the cases exercise.

    coverage.py --cases DIR [--cases DIR ...] --md COVERAGE.md   # regenerate the map
    coverage.py --cases DIR ... --find '\\looseness'             # cases using a primitive
    coverage.py --cases DIR ... --sections 'Breaking paragraphs' # uncited sections in a part

Later --cases directories override earlier ones for the same file name, so a
reference set can be built as "main, then each open PR". Section numbers follow
the corpus rule: count lines starting `@ ` or `@*` from 1 (the lone `@` lines
in pdftex.web count too).

A section is "cited" when a case's first line names it after `tex.web` or
`pdftex.web` (`§§332, 1058`, ranges `656-657`). A primitive is "used" when it
appears as a control word in a non-comment line of the case body. The map says
what the corpus already touches; it does not say a citation is right, and the
side-by-side read of any candidate pair is still required.
"""
import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WEBS = {"tex.web": ROOT / "third_party/knuth/tex.web",
        "pdftex.web": ROOT / "third_party/pdftex/pdftex.web"}
BOILER = re.compile(r"^\\(font|textfont|scriptfont|scriptscriptfont)\b|^\\input\s+prelude|^\\lsshipbox")
CS = re.compile(r"\\([A-Za-z]+)")
MARK = re.compile(r"(?<![\w.])(pdftex\.web|tex\.web)")
NUM = re.compile(r"(\d+)(?:\s*-\s*(\d+))?")


def load_web(path):
    """Return (sections: {n: (part_title, first_words)}, primitives: set)."""
    text = path.read_text(encoding="latin-1")
    sections, part, n = {}, "", 0
    for line in text.split("\n"):
        if line.startswith("@*"):
            n += 1
            part = re.sub(r"\.\s*$", "", line[2:].split(".")[0]).strip()
            sections[n] = (part, part)
        elif line.startswith("@ ") or line == "@":
            n += 1
            sections[n] = (part, line[2:60].strip())
    prims = set(re.findall(r'primitive\("([^"]+)"', text))
    return sections, prims


def load_cases(dirs):
    cases = {}
    for d in dirs:
        for f in Path(d).glob("*.tex"):
            cases[f.name] = f
    return dict(sorted(cases.items()))


def cited(first_line):
    """{web: set(section numbers)} from a case header line."""
    out = defaultdict(set)
    if not first_line.startswith("%"):
        return out
    parts = MARK.split(first_line)
    for i in range(1, len(parts) - 1, 2):
        web, tail = parts[i], parts[i + 1]
        tail = tail.split(";")[0].split(")")[0]
        for m in NUM.finditer(tail):
            lo = int(m.group(1))
            hi = int(m.group(2) or lo)
            if hi - lo < 200:
                out[web].update(range(lo, hi + 1))
    return out


def analyse(cases, prims_universe):
    sec = {w: defaultdict(list) for w in WEBS}
    prim = defaultdict(list)
    uncited = []
    for name, path in cases.items():
        lines = path.read_text(encoding="latin-1").split("\n")
        c = cited(lines[0] if lines else "")
        if not any(c.values()):
            uncited.append(name)
        for web, nums in c.items():
            for n in nums:
                sec[web][n].append(name)
        used = set()
        for ln in lines:
            if ln.startswith("%") or BOILER.match(ln):
                continue
            ln = re.sub(r"(?<!\\)%.*", "", ln)
            used.update(w for w in CS.findall(ln) if w in prims_universe)
        for w in used:
            prim[w].append(name)
    return sec, prim, uncited


def short(names):
    return " ".join(n.split("-")[0] for n in names)


def render(cases, webs, sec, prim, uncited, prims_universe, refs):
    o = ["# Lockstep corpus coverage map", "",
         "Generated by `tools/lockstep/coverage.py`; do not edit by hand. Regenerate with the same "
         "`--cases` list after the corpus changes. Before writing a case, run "
         "`coverage.py --cases ... --find '\\primitive'` and read every hit side by side.", "",
         f"Reference set: {len(cases)} cases from {refs}.", "",
         f"Cases with no parsable `tex.web`/`pdftex.web` citation on line 1: {len(uncited)}. "
         "Those cases count in the primitive index but not in the section tables, so the section "
         "tables undercount coverage; trust the primitive index first.", ""]
    zero = sorted(p for p in prims_universe if p not in prim)
    one = sorted(p for p in prims_universe if len(prim.get(p, ())) == 1)
    o += [f"## Primitives ({len(prims_universe)} in tex.web + pdftex.web)", "",
          f"- Used by no case ({len(zero)}): " + (" ".join("`\\%s`" % p for p in zero) or "none"), "",
          f"- Used by exactly one case ({len(one)}): "
          + (" ".join("`\\%s`=%s" % (p, prim[p][0].split("-")[0]) for p in one) or "none"), "",
          "Note: 'used' includes incidental use, e.g. `\\hbox` in a case about something else; "
          "grep the key primitive, not the count.", ""]
    for web, (sections, _) in webs.items():
        by_part = defaultdict(lambda: [0, 0, 0])
        for n, (part, _t) in sections.items():
            k = len(sec[web].get(n, ()))
            by_part[part][0] += 1
            by_part[part][1] += k >= 1
            by_part[part][2] += k >= 2
        o += [f"## {web}: sections cited per part", "",
              "| Part | Sections | Cited by >=1 case | Cited by >=2 cases |", "|---|---|---|---|"]
        for part, (t, c1, c2) in by_part.items():
            o.append(f"| {part} | {t} | {c1} | {c2} |")
        o += ["", f"Sections cited by exactly one case: "
              + (" ".join("§%d=%s" % (n, sec[web][n][0].split("-")[0])
                          for n in sorted(sec[web]) if len(sec[web][n]) == 1) or "none"), ""]
    o += ["## Primitive index", "", "Primitive: case numbers.", ""]
    for p in sorted(prim):
        o.append(f"- `\\{p}`: {short(prim[p])}")
    return "\n".join(o) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--cases", action="append", required=True, help="case directory (repeatable, later wins)")
    ap.add_argument("--md", help="write the map to this file")
    ap.add_argument("--find", help=r"list cases using this primitive, e.g. \looseness")
    ap.add_argument("--sections", help="list uncited sections of the part whose title contains this text")
    ap.add_argument("--refs", default="see the PR that regenerated this file", help="text for the header")
    a = ap.parse_args(argv)
    cases = load_cases(a.cases)
    webs, universe = {}, set()
    for w, p in WEBS.items():
        webs[w] = load_web(p)
        universe |= webs[w][1]
    sec, prim, uncited = analyse(cases, universe)
    if a.find:
        want = a.find.lstrip("\\")
        for name in prim.get(want, []):
            print(f"{name}: {cases[name].read_text(encoding='latin-1').split(chr(10))[0][:170]}")
        print(f"{len(prim.get(want, []))} case(s) use \\{want}", file=sys.stderr)
    if a.sections:
        for w, (sections, _) in webs.items():
            for n, (part, t) in sections.items():
                if a.sections.lower() in part.lower() and not sec[w].get(n):
                    print(f"{w} §{n} [{part}] {t}")
    if a.md:
        Path(a.md).write_text(render(cases, webs, sec, prim, uncited, universe, a.refs))
    if not (a.find or a.sections or a.md):
        ap.error("give --md, --find or --sections")
    return 0


if __name__ == "__main__":
    sys.exit(main())
