// @generated by crates/class-geometry/tools/gen_class_tables.py -- do not edit.
// Provenance: pdfTeX 3.141592653-2.6-1.40.29 (TeX Live 2026); class `article` at 10pt/11pt/12pt with default options (letter paper, oneside, onecolumn).
// Probe: `\documentclass[<size>]{article}` printing `\the<param>` via `\typeout{FTDIM ...}` after `\begin{document}` (see the generator script header for the full probe document).
// `columnwidth` is intentionally absent: it derives from `textwidth`/`columnsep` via `PageParams::columnwidth`.
#![allow(clippy::all)]

use crate::class::{BaseSize, Glue};
use crate::tex::Sp;

/// `article` layout parameters measured from real pdflatex
/// (`PageParams` field order, plus the body-font em/ex).
/// Glue is `(natural, stretch, shrink)` in scaled points.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ArticleLayout {
    pub size: BaseSize,
    pub paperwidth: Sp,
    pub paperheight: Sp,
    pub textwidth: Sp,
    pub textheight: Sp,
    pub oddsidemargin: Sp,
    pub evensidemargin: Sp,
    pub topmargin: Sp,
    pub headheight: Sp,
    pub headsep: Sp,
    pub footskip: Sp,
    pub topskip: Sp,
    pub baselineskip: Sp,
    pub parindent: Sp,
    pub marginparwidth: Sp,
    pub marginparsep: Sp,
    pub marginparpush: Sp,
    pub columnsep: Sp,
    pub columnseprule: Sp,
    pub maxdepth: Sp,
    pub footnotesep: Sp,
    pub overfullrule: Sp,
    pub leftmargini: Sp,
    pub labelsep: Sp,
    pub hoffset: Sp,
    pub voffset: Sp,
    pub parskip: Glue,
    pub skip_footins: Glue,
    pub mathindent: Option<Sp>,
    pub em: Sp,
    pub ex: Sp,
}

/// `article`, `10pt`, default options, per pdflatex.
pub static ARTICLE_10PT: ArticleLayout = ArticleLayout {
    size: BaseSize::Pt10,
    paperwidth: Sp(40258437), // 614.295pt
    paperheight: Sp(52099153), // 794.96999pt
    textwidth: Sp(22609920), // 345.0pt
    textheight: Sp(36044800), // 550.0pt
    oddsidemargin: Sp(4063232), // 62.0pt
    evensidemargin: Sp(4063232), // 62.0pt
    topmargin: Sp(1048576), // 16.0pt
    headheight: Sp(786432), // 12.0pt
    headsep: Sp(1638400), // 25.0pt
    footskip: Sp(1966080), // 30.0pt
    topskip: Sp(655360), // 10.0pt
    baselineskip: Sp(786432), // 12.0pt
    parindent: Sp(983040), // 15.0pt
    marginparwidth: Sp(4259840), // 65.0pt
    marginparsep: Sp(720896), // 11.0pt
    marginparpush: Sp(327680), // 5.0pt
    columnsep: Sp(655360), // 10.0pt
    columnseprule: Sp(0), // 0.0pt
    maxdepth: Sp(327680), // 5.0pt
    footnotesep: Sp(435814), // 6.65pt
    overfullrule: Sp(0), // 0.0pt
    leftmargini: Sp(1638402), // 25.00003pt
    labelsep: Sp(327680), // 5.0pt
    hoffset: Sp(0), // 0.0pt
    voffset: Sp(0), // 0.0pt
    parskip: Glue { natural: Sp(0), stretch: Sp(65536), shrink: Sp(0) }, // 0.0pt plus 1.0pt
    skip_footins: Glue { natural: Sp(589824), stretch: Sp(262144), shrink: Sp(131072) }, // 9.0pt plus 4.0pt minus 2.0pt
    mathindent: None, // \mathindent undefined without fleqn
    em: Sp(655361), // 10.00002pt
    ex: Sp(282168), // 4.30554pt
};

/// `article`, `11pt`, default options, per pdflatex.
pub static ARTICLE_11PT: ArticleLayout = ArticleLayout {
    size: BaseSize::Pt11,
    paperwidth: Sp(40258437), // 614.295pt
    paperheight: Sp(52099153), // 794.96999pt
    textwidth: Sp(23592960), // 360.0pt
    textheight: Sp(35481206), // 541.40024pt
    oddsidemargin: Sp(3538944), // 54.0pt
    evensidemargin: Sp(3604480), // 55.0pt
    topmargin: Sp(1376256), // 21.0pt
    headheight: Sp(786432), // 12.0pt
    headsep: Sp(1638400), // 25.0pt
    footskip: Sp(1966080), // 30.0pt
    topskip: Sp(720896), // 11.0pt
    baselineskip: Sp(891290), // 13.6pt
    parindent: Sp(1114112), // 17.0pt
    marginparwidth: Sp(3866624), // 59.0pt
    marginparsep: Sp(655360), // 10.0pt
    marginparpush: Sp(327680), // 5.0pt
    columnsep: Sp(655360), // 10.0pt
    columnseprule: Sp(0), // 0.0pt
    maxdepth: Sp(360448), // 5.5pt
    footnotesep: Sp(504627), // 7.7pt
    overfullrule: Sp(0), // 0.0pt
    leftmargini: Sp(1794052), // 27.37506pt
    labelsep: Sp(358810), // 5.475pt
    hoffset: Sp(0), // 0.0pt
    voffset: Sp(0), // 0.0pt
    parskip: Glue { natural: Sp(0), stretch: Sp(65536), shrink: Sp(0) }, // 0.0pt plus 1.0pt
    skip_footins: Glue { natural: Sp(655360), stretch: Sp(262144), shrink: Sp(131072) }, // 10.0pt plus 4.0pt minus 2.0pt
    mathindent: None, // \mathindent undefined without fleqn
    em: Sp(717621), // 10.95003pt
    ex: Sp(308974), // 4.71457pt
};

/// `article`, `12pt`, default options, per pdflatex.
pub static ARTICLE_12PT: ArticleLayout = ArticleLayout {
    size: BaseSize::Pt12,
    paperwidth: Sp(40258437), // 614.295pt
    paperheight: Sp(52099153), // 794.96999pt
    textwidth: Sp(25559040), // 390.0pt
    textheight: Sp(35946496), // 548.5pt
    oddsidemargin: Sp(2555904), // 39.0pt
    evensidemargin: Sp(2621440), // 40.0pt
    topmargin: Sp(1114112), // 17.0pt
    headheight: Sp(786432), // 12.0pt
    headsep: Sp(1638400), // 25.0pt
    footskip: Sp(1966080), // 30.0pt
    topskip: Sp(786432), // 12.0pt
    baselineskip: Sp(950272), // 14.5pt
    parindent: Sp(1155060), // 17.62482pt
    marginparwidth: Sp(2883584), // 44.0pt
    marginparsep: Sp(655360), // 10.0pt
    marginparpush: Sp(458752), // 7.0pt
    columnsep: Sp(655360), // 10.0pt
    columnseprule: Sp(0), // 0.0pt
    maxdepth: Sp(393216), // 6.0pt
    footnotesep: Sp(550502), // 8.4pt
    overfullrule: Sp(0), // 0.0pt
    leftmargini: Sp(1925100), // 29.3747pt
    labelsep: Sp(385020), // 5.87494pt
    hoffset: Sp(0), // 0.0pt
    voffset: Sp(0), // 0.0pt
    parskip: Glue { natural: Sp(0), stretch: Sp(65536), shrink: Sp(0) }, // 0.0pt plus 1.0pt
    skip_footins: Glue { natural: Sp(707789), stretch: Sp(262144), shrink: Sp(131072) }, // 10.8pt plus 4.0pt minus 2.0pt
    mathindent: None, // \mathindent undefined without fleqn
    em: Sp(770040), // 11.74988pt
    ex: Sp(338603), // 5.16667pt
};

/// The three generated `article` tables, by size.
pub static ARTICLE_TABLES: [&ArticleLayout; 3] =
    [&ARTICLE_10PT, &ARTICLE_11PT, &ARTICLE_12PT];

/// Look up the generated `article` table for a base size.
pub fn article_layout(size: BaseSize) -> &'static ArticleLayout {
    match size {
        BaseSize::Pt10 => &ARTICLE_10PT,
        BaseSize::Pt11 => &ARTICLE_11PT,
        BaseSize::Pt12 => &ARTICLE_12PT,
    }
}
