// name: FlashTeXJsonContext.cs
// purpose: System.Text.Json source-generation context covering every DTO across
//   all four wire protocols (runtime-v1, transfer-v1, capture, rendering-v2), so
//   (de)serialization is reflection-free and AOT-safe by construction — this is
//   the direct C# replacement for the Swift package's hand-rolled fast-path JSON
//   scanner (RenderingV2Fast.swift), which System.Text.Json source generation
//   makes unnecessary.
// author: Claude Sonnet 5
// date: 2026-09-13

using System.Text.Json;
using System.Text.Json.Serialization;
using FlashTeX.Protocol.EditLedgerV1;
using FlashTeX.Protocol.ProjectFilesV1;
using FlashTeX.Protocol.RenderingV2;
using FlashTeX.Protocol.RuntimeV1;
using FlashTeX.Protocol.TransferV1;

namespace FlashTeX.Protocol;

// MARK: runtime-v1 and capture

[JsonSerializable(typeof(Envelope<CompileRequest>))]
[JsonSerializable(typeof(Envelope<CompileResult>))]
[JsonSerializable(typeof(Envelope<CaptureSubmit>))]
[JsonSerializable(typeof(Envelope<CaptureProposal>))]
[JsonSerializable(typeof(Document))]
[JsonSerializable(typeof(SourceRange))]
[JsonSerializable(typeof(CompileRequest))]
[JsonSerializable(typeof(CompileRequest.DisplayListBaseInfo))]
[JsonSerializable(typeof(Status))]
[JsonSerializable(typeof(Severity), TypeInfoPropertyName = "RuntimeV1Severity")]
[JsonSerializable(typeof(RuntimeV1.Diagnostic), TypeInfoPropertyName = "RuntimeV1Diagnostic")]
[JsonSerializable(typeof(RuntimeV1.Page), TypeInfoPropertyName = "RuntimeV1Page")]
// The generator's auto-derived collection-wrapper names collide across namespaces
// (e.g. "IReadOnlyListPage" for both RuntimeV1.Page and RenderingV2.Page collections)
// even after the element types above are disambiguated, so the collections
// CompileResult.Pages/.Diagnostics and DisplayList.Pages/.Diagnostics need their own
// explicit, disambiguated entries too.
[JsonSerializable(typeof(IReadOnlyList<RuntimeV1.Page>), TypeInfoPropertyName = "RuntimeV1PageList")]
[JsonSerializable(typeof(IReadOnlyList<RuntimeV1.Diagnostic>), TypeInfoPropertyName = "RuntimeV1DiagnosticList")]
[JsonSerializable(typeof(PageItem))]
[JsonSerializable(typeof(PageItem.TextItem))]
[JsonSerializable(typeof(PageItem.RuleItem))]
[JsonSerializable(typeof(PageItem.FontHint))]
[JsonSerializable(typeof(PageItem.FontHint.FontWeight))]
[JsonSerializable(typeof(PageItem.FontHint.FontStyle))]
[JsonSerializable(typeof(CompileResult))]
[JsonSerializable(typeof(CaptureImage))]
[JsonSerializable(typeof(CaptureSubmit))]
[JsonSerializable(typeof(RuntimeV1.CaptureReceived), TypeInfoPropertyName = "RuntimeV1CaptureReceived")]
[JsonSerializable(typeof(CaptureProposal))]
[JsonSerializable(typeof(EnvelopeHeader))]
[JsonSerializable(typeof(RuntimeV1.ErrorPayload), TypeInfoPropertyName = "RuntimeV1ErrorPayload")]

// MARK: transfer-v1

[JsonSerializable(typeof(Envelope<TransferV1.ErrorPayload>))]
[JsonSerializable(typeof(Envelope<Empty>))]
[JsonSerializable(typeof(Envelope<DocumentOpen>))]
[JsonSerializable(typeof(Envelope<DocumentEdit>))]
[JsonSerializable(typeof(Envelope<DocumentUpdated>))]
[JsonSerializable(typeof(Envelope<DestinationPin>))]
[JsonSerializable(typeof(Envelope<Anchor>))]
[JsonSerializable(typeof(Envelope<TransferV1.CaptureReceived>), TypeInfoPropertyName = "EnvelopeTransferV1CaptureReceived")]
[JsonSerializable(typeof(Envelope<CaptureConvert>))]
[JsonSerializable(typeof(Envelope<CaptureId>))]
[JsonSerializable(typeof(Envelope<CapturePrepareInsert>))]
[JsonSerializable(typeof(Envelope<CaptureEdit>))]
[JsonSerializable(typeof(Envelope<CaptureApplied>))]
[JsonSerializable(typeof(Envelope<CaptureStatus>))]
[JsonSerializable(typeof(TransferV1.ErrorPayload), TypeInfoPropertyName = "TransferV1ErrorPayload")]
[JsonSerializable(typeof(Empty))]
[JsonSerializable(typeof(DocumentOpen))]
[JsonSerializable(typeof(DocumentEdit))]
[JsonSerializable(typeof(DocumentUpdated))]
[JsonSerializable(typeof(DestinationPin))]
[JsonSerializable(typeof(AnchorBinding))]
[JsonSerializable(typeof(Anchor))]
[JsonSerializable(typeof(TransferV1.CaptureReceived), TypeInfoPropertyName = "TransferV1CaptureReceived")]
[JsonSerializable(typeof(CaptureConvert))]
[JsonSerializable(typeof(CaptureId))]
[JsonSerializable(typeof(CapturePrepareInsert))]
[JsonSerializable(typeof(CaptureEdit))]
[JsonSerializable(typeof(CaptureApplied))]
[JsonSerializable(typeof(Proposal))]
[JsonSerializable(typeof(AppliedEdit))]
[JsonSerializable(typeof(CaptureStatus))]

// MARK: rendering-v2 (display-list-v2)

[JsonSerializable(typeof(RenderingV2.Envelope))]
[JsonSerializable(typeof(Ticks))]
[JsonSerializable(typeof(Paint))]
[JsonSerializable(typeof(Rect))]
[JsonSerializable(typeof(Caret))]
[JsonSerializable(typeof(Cluster))]
[JsonSerializable(typeof(Glyph))]
[JsonSerializable(typeof(GlyphRun))]
[JsonSerializable(typeof(Rule))]
[JsonSerializable(typeof(ImageResource))]
[JsonSerializable(typeof(Image))]
[JsonSerializable(typeof(PathCommand))]
[JsonSerializable(typeof(FillRule))]
[JsonSerializable(typeof(LineCap))]
[JsonSerializable(typeof(LineJoin))]
[JsonSerializable(typeof(Dash))]
[JsonSerializable(typeof(Stroke))]
[JsonSerializable(typeof(ClipPath))]
[JsonSerializable(typeof(RenderingV2.Path))]
[JsonSerializable(typeof(Item))]
[JsonSerializable(typeof(RenderingV2.Page), TypeInfoPropertyName = "RenderingV2Page")]
[JsonSerializable(typeof(FontResource))]
[JsonSerializable(typeof(DocumentResource))]
[JsonSerializable(typeof(RenderingV2.Diagnostic), TypeInfoPropertyName = "RenderingV2Diagnostic")]
[JsonSerializable(typeof(RenderingV2.Diagnostic.Severity), TypeInfoPropertyName = "RenderingV2DiagnosticSeverity")]
[JsonSerializable(typeof(IReadOnlyList<RenderingV2.Page>), TypeInfoPropertyName = "RenderingV2PageList")]
[JsonSerializable(typeof(IReadOnlyList<RenderingV2.Diagnostic>), TypeInfoPropertyName = "RenderingV2DiagnosticList")]
[JsonSerializable(typeof(DisplayList))]

// MARK: project-files-v1

[JsonSerializable(typeof(ProjectFilesV1.PingRequest))]
[JsonSerializable(typeof(ProjectFilesV1.ReadRequest))]
[JsonSerializable(typeof(ProjectFilesV1.StatusRequest))]
[JsonSerializable(typeof(ProjectFilesV1.SaveRequest))]
[JsonSerializable(typeof(ProjectFilesV1.PingPayload))]
[JsonSerializable(typeof(ProjectFilesV1.ReadPayload))]
[JsonSerializable(typeof(ProjectFilesV1.DiskState))]
[JsonSerializable(typeof(ProjectFilesV1.StatusPayload))]
[JsonSerializable(typeof(ProjectFilesV1.SaveReceipt))]
[JsonSerializable(typeof(ProjectFilesV1.ConflictKind))]
[JsonSerializable(typeof(ProjectFilesV1.SaveConflict))]
[JsonSerializable(typeof(ProjectFilesV1.SaveOutcomeWire))]
[JsonSerializable(typeof(ProjectFilesV1.ErrorPayload), TypeInfoPropertyName = "ProjectFilesV1ErrorPayload")]

// MARK: edit-ledger-v1

[JsonSerializable(typeof(EditLedgerDocument))]
[JsonSerializable(typeof(EditLedgerV1.AppliedTransaction))]
[JsonSerializable(typeof(InitializeRequest))]
[JsonSerializable(typeof(ApplyRequest))]
[JsonSerializable(typeof(ReplaceDocumentRequest))]
[JsonSerializable(typeof(ConfirmRequest))]
[JsonSerializable(typeof(EditLedgerV1.StatusRequest), TypeInfoPropertyName = "EditLedgerStatusRequest")]
[JsonSerializable(typeof(RecoveryExportRequest))]
[JsonSerializable(typeof(RecoveryImportRequest))]
[JsonSerializable(typeof(CompactRequest))]
[JsonSerializable(typeof(ApplyGroupRequest))]
[JsonSerializable(typeof(UndoRequest))]
[JsonSerializable(typeof(RedoRequest))]
[JsonSerializable(typeof(RetainHistoryRequest))]
[JsonSerializable(typeof(HistoryStatusRequest))]
[JsonSerializable(typeof(EditLedgerV1.CheckpointStatusRequest))]
[JsonSerializable(typeof(CheckpointRotateRequest))]
[JsonSerializable(typeof(CheckpointReadRequest))]
[JsonSerializable(typeof(CheckpointExportRequest))]
[JsonSerializable(typeof(CheckpointPlanRequest))]
[JsonSerializable(typeof(CheckpointImportRequest))]
[JsonSerializable(typeof(InitializeResult))]
[JsonSerializable(typeof(ApplyResult))]
[JsonSerializable(typeof(ReplaceDocumentResult))]
[JsonSerializable(typeof(ConfirmResult))]
[JsonSerializable(typeof(EditLedgerV1.StatusResult))]
[JsonSerializable(typeof(CheckpointImportResult))]
[JsonSerializable(typeof(RecoveryExport))]
[JsonSerializable(typeof(RecoveryImport))]
[JsonSerializable(typeof(BridgeObservation))]
[JsonSerializable(typeof(BridgeObservation.Applied))]
[JsonSerializable(typeof(BridgeObservation.Prepared))]
[JsonSerializable(typeof(BridgeObservation.Unavailable))]
[JsonSerializable(typeof(RecoveryAction))]
[JsonSerializable(typeof(RecoveryAction.Confirmed))]
[JsonSerializable(typeof(RecoveryAction.ReplayReceipt))]
[JsonSerializable(typeof(RecoveryAction.RetryStatus))]
[JsonSerializable(typeof(RecoveryPlan))]
[JsonSerializable(typeof(RetentionPolicy))]
[JsonSerializable(typeof(CompactionReport))]
[JsonSerializable(typeof(SourceEdit))]
[JsonSerializable(typeof(GroupedEdit))]
[JsonSerializable(typeof(HistoryMove))]
[JsonSerializable(typeof(HistoryResult))]
[JsonSerializable(typeof(HistoryRetentionPolicy))]
[JsonSerializable(typeof(HistoryRetentionReport))]
[JsonSerializable(typeof(HistoryStatusResult))]
[JsonSerializable(typeof(EditLedgerV1.StoreIdentity))]
[JsonSerializable(typeof(CheckpointInfo))]
[JsonSerializable(typeof(ExportAuthorization))]
[JsonSerializable(typeof(RotationPolicy))]
[JsonSerializable(typeof(RotationReport))]
[JsonSerializable(typeof(EditLedgerV1.CheckpointStatusResult))]
[JsonSerializable(typeof(EditLedgerV1.Checkpoint))]
[JsonSerializable(typeof(ImportAction))]
[JsonSerializable(typeof(ImportPlan))]
[JsonSerializable(typeof(ImportAuthorization))]
[JsonSerializable(typeof(ServiceReply<InitializeResult>))]
[JsonSerializable(typeof(ServiceReply<ApplyResult>))]
[JsonSerializable(typeof(ServiceReply<ReplaceDocumentResult>))]
[JsonSerializable(typeof(ServiceReply<ConfirmResult>))]
[JsonSerializable(typeof(ServiceReply<EditLedgerV1.StatusResult>))]
[JsonSerializable(typeof(ServiceReply<RecoveryExport>))]
[JsonSerializable(typeof(ServiceReply<RecoveryPlan>))]
[JsonSerializable(typeof(ServiceReply<CompactionReport>))]
[JsonSerializable(typeof(ServiceReply<HistoryResult>))]
[JsonSerializable(typeof(ServiceReply<HistoryStatusResult>))]
[JsonSerializable(typeof(ServiceReply<HistoryRetentionReport>))]
[JsonSerializable(typeof(ServiceReply<EditLedgerV1.CheckpointStatusResult>))]
[JsonSerializable(typeof(ServiceReply<RotationReport>))]
[JsonSerializable(typeof(ServiceReply<EditLedgerV1.Checkpoint>))]
[JsonSerializable(typeof(ServiceReply<ImportPlan>))]
[JsonSerializable(typeof(ServiceReply<CheckpointImportResult>))]

// MARK: preview-controller-v1
// Not brought in via `using` (its own `Envelope<T>`/`ErrorPayload` would collide
// with runtime-v1's above), so every entry below is fully qualified and every
// `Envelope<T>`/`ErrorPayload` closure gets an explicit disambiguated name.

[JsonSerializable(typeof(PreviewControllerV1.LaunchConfig))]
[JsonSerializable(typeof(PreviewControllerV1.ErrorPayload), TypeInfoPropertyName = "PreviewControllerErrorPayload")]
[JsonSerializable(typeof(PreviewControllerV1.PreviewDocument))]
[JsonSerializable(typeof(PreviewControllerV1.SourceSpan))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, ulong>), TypeInfoPropertyName = "SourceVersionsMap")]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>), TypeInfoPropertyName = "DocumentKindsMap")]

// Request payloads and their `Envelope<T>` closures.
[JsonSerializable(typeof(PreviewControllerV1.PathPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.PathPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopePathPayload")]
[JsonSerializable(typeof(PreviewControllerV1.EditPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.EditPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeEditPayload")]
[JsonSerializable(typeof(PreviewControllerV1.CompilePayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.CompilePayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeCompilePayload")]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<Empty>), TypeInfoPropertyName = "PreviewControllerEnvelopeEmpty")]
[JsonSerializable(typeof(PreviewControllerV1.ReviewPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.ReviewPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeReviewPayload")]
[JsonSerializable(typeof(PreviewControllerV1.ApplyReviewedPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.ApplyReviewedPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeApplyReviewedPayload")]
[JsonSerializable(typeof(PreviewControllerV1.ApprovalTokenPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.ApprovalTokenPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeApprovalTokenPayload")]
[JsonSerializable(typeof(PreviewControllerV1.ConfirmReceiptPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.ConfirmReceiptPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeConfirmReceiptPayload")]
[JsonSerializable(typeof(PreviewControllerV1.CompletePayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.CompletePayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeCompletePayload")]
[JsonSerializable(typeof(PreviewControllerV1.NavigatePayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.NavigatePayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeNavigatePayload")]
[JsonSerializable(typeof(PreviewControllerV1.ApplyGroupPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.ApplyGroupPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeApplyGroupPayload")]
[JsonSerializable(typeof(PreviewControllerV1.HistoryMovePayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.HistoryMovePayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeHistoryMovePayload")]
[JsonSerializable(typeof(PreviewControllerV1.ConfigureLayoutPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.ConfigureLayoutPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeConfigureLayoutPayload")]
[JsonSerializable(typeof(PreviewControllerV1.ExportPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.ExportPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeExportPayload")]
[JsonSerializable(typeof(PreviewControllerV1.ReloadPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.ReloadPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeReloadPayload")]
[JsonSerializable(typeof(PreviewControllerV1.MembershipPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.MembershipPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeMembershipPayload")]
[JsonSerializable(typeof(PreviewControllerV1.ProjectStatusPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.ProjectStatusPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeProjectStatusPayload")]
[JsonSerializable(typeof(PreviewControllerV1.SearchLiteralPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.SearchLiteralPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeSearchLiteralPayload")]
[JsonSerializable(typeof(PreviewControllerV1.PlanLiteralReplacementPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.PlanLiteralReplacementPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopePlanLiteralReplacementPayload")]
[JsonSerializable(typeof(PreviewControllerV1.PlanCitationRenamePayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.PlanCitationRenamePayload>), TypeInfoPropertyName = "PreviewControllerEnvelopePlanCitationRenamePayload")]
[JsonSerializable(typeof(PreviewControllerV1.PlanCitationRenameAtPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.PlanCitationRenameAtPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopePlanCitationRenameAtPayload")]
[JsonSerializable(typeof(PreviewControllerV1.ConfigureDisplayCandidatesPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.ConfigureDisplayCandidatesPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeConfigureDisplayCandidatesPayload")]
[JsonSerializable(typeof(PreviewControllerV1.ConfigureCompletedSnapshotsPayload))]
[JsonSerializable(typeof(PreviewControllerV1.Envelope<PreviewControllerV1.ConfigureCompletedSnapshotsPayload>), TypeInfoPropertyName = "PreviewControllerEnvelopeConfigureCompletedSnapshotsPayload")]

// Reply payloads.
[JsonSerializable(typeof(PreviewControllerV1.DocumentResult))]
[JsonSerializable(typeof(PreviewControllerV1.EditResult))]
[JsonSerializable(typeof(PreviewControllerV1.SubmittedResult))]
[JsonSerializable(typeof(PreviewControllerV1.ClosedResult))]
[JsonSerializable(typeof(PreviewControllerV1.ReviewResult))]
[JsonSerializable(typeof(PreviewControllerV1.ApplyReviewedResult))]
[JsonSerializable(typeof(PreviewControllerV1.RetiredResult))]
[JsonSerializable(typeof(PreviewControllerV1.RecoveryResult))]
[JsonSerializable(typeof(PreviewControllerV1.ConfirmedResult))]
[JsonSerializable(typeof(PreviewControllerV1.SnapshotResult))]
[JsonSerializable(typeof(PreviewControllerV1.CompletionItem))]
[JsonSerializable(typeof(PreviewControllerV1.CompleteResult))]
[JsonSerializable(typeof(PreviewControllerV1.NavigationHit))]
[JsonSerializable(typeof(PreviewControllerV1.NavigateResult))]
[JsonSerializable(typeof(PreviewControllerV1.HistoryLimits))]
[JsonSerializable(typeof(PreviewControllerV1.HistoryStatusDocument))]
[JsonSerializable(typeof(PreviewControllerV1.HistoryStatusReply))]
[JsonSerializable(typeof(PreviewControllerV1.PreviewHistoryResult))]
[JsonSerializable(typeof(PreviewControllerV1.ApplyHistoryResult))]
[JsonSerializable(typeof(PreviewControllerV1.FileDiskState))]
[JsonSerializable(typeof(PreviewControllerV1.FileDiskState.MatchesSource), TypeInfoPropertyName = "FileDiskStateMatchesSource")]
[JsonSerializable(typeof(PreviewControllerV1.FileDiskState.DiffersFromSource), TypeInfoPropertyName = "FileDiskStateDiffersFromSource")]
[JsonSerializable(typeof(PreviewControllerV1.FileDiskState.Missing), TypeInfoPropertyName = "FileDiskStateMissing")]
[JsonSerializable(typeof(PreviewControllerV1.FileDiskState.Unavailable), TypeInfoPropertyName = "FileDiskStateUnavailable")]
[JsonSerializable(typeof(PreviewControllerV1.FileStatusResult))]
[JsonSerializable(typeof(PreviewControllerV1.ExportResult))]
[JsonSerializable(typeof(PreviewControllerV1.ReloadResult))]
[JsonSerializable(typeof(PreviewControllerV1.MembershipResult))]
[JsonSerializable(typeof(PreviewControllerV1.ProjectStatusDocument))]
[JsonSerializable(typeof(PreviewControllerV1.ProjectStatusResult))]
[JsonSerializable(typeof(PreviewControllerV1.SearchTermination))]
[JsonSerializable(typeof(PreviewControllerV1.SearchResult))]
[JsonSerializable(typeof(PreviewControllerV1.PlanResult))]
[JsonSerializable(typeof(PreviewControllerV1.DisplayCandidatesResult))]
[JsonSerializable(typeof(PreviewControllerV1.CompletedSnapshotsResult))]

// Unsolicited frames.
[JsonSerializable(typeof(PreviewControllerV1.ReadyPayload))]
[JsonSerializable(typeof(PreviewControllerV1.PreviewUpdate))]
[JsonSerializable(typeof(PreviewControllerV1.PreviewUpdate.Preview))]
[JsonSerializable(typeof(PreviewControllerV1.PreviewUpdate.Discarded))]
[JsonSerializable(typeof(PreviewControllerV1.PreviewUpdate.Superseded))]
[JsonSerializable(typeof(PreviewControllerV1.PreviewUpdate.Stale))]
[JsonSerializable(typeof(PreviewControllerV1.PreviewUpdate.Cancelled))]
[JsonSerializable(typeof(PreviewControllerV1.PreviewUpdate.Failed))]
[JsonSerializable(typeof(PreviewControllerV1.PreviewUpdate.CompletedSnapshot))]
[JsonSerializable(typeof(PreviewControllerV1.PreviewUpdate.DisplayCandidate))]
[JsonSourceGenerationOptions(WriteIndented = false)]
public sealed partial class FlashTeXJsonContext : JsonSerializerContext
{
}

/// <summary>Ready-to-use options wired to <see cref="FlashTeXJsonContext"/>; reflection-free and AOT-safe.</summary>
public static class FlashTeXJson
{
    public static readonly JsonSerializerOptions Options = new()
    {
        TypeInfoResolver = FlashTeXJsonContext.Default,
    };
}
