"""Who defines a construct FlashTeX did not know? (root-cause grouping)

Oracle tooling only (standard library). A diagnostic names a construct
(`\\texorpdfstring`, `\\subjclass`, environment `alignat`); the construct
itself is rarely the root cause -- the package or class that defines it is,
and one package usually brings a dozen of them. This module answers "who
defines it" from the *sources*, never from FlashTeX:

1. the document's own files (a `\\newcommand`/`\\def` in the project's .tex,
   or a project-local .sty/.cls) -> `project: .tex` / `project: .sty/.cls`;
2. the TeX Live tree (`tex/latex`, `tex/generic`), indexed once by a regex
   over every `.sty`/`.cls`/`.ltx`/`.def` for definitions (`\\def`,
   `\\newcommand`, `\\DeclareRobustCommand`, `\\DeclareMathSymbol`,
   `\\newenvironment`, `\\newtheorem`, ...) -> `class X` / `package X` /
   `LaTeX kernel`, preferring a definer the document actually loads.

The index is cached in the parity cache keyed by the tree's path and the
modification time of its `ls-R` database. It is a heuristic: a construct
generated by `\\csname` or defined in a `.dtx`-only file is not found and
keeps its own key.
"""

import json
import os
import re

DEF_CS = re.compile(
    rb"\\(?:def|gdef|edef|xdef|let|global\\def|global\\let|global\\edef|chardef|mathchardef|countdef|dimendef|"
    rb"skipdef|toksdef|newcount|newdimen|newskip|newtoks|newbox|newif)\s*\\([A-Za-z@]+)"
    rb"|\\(?:newcommand|renewcommand|providecommand|DeclareRobustCommand|DeclareMathOperator|NewDocumentCommand|"
    rb"DeclareDocumentCommand|ProvideDocumentCommand|RenewDocumentCommand|newrobustcmd|renewrobustcmd|"
    rb"providerobustcmd|DeclareMathSymbol|DeclareMathAlphabet|DeclareMathDelimiter|DeclareMathAccent|"
    rb"DeclareMathRadical|DeclareTextCommand|DeclareTextSymbol|DeclareTextAccent|DeclareTextCommandDefault|"
    rb"DeclareTextSymbolDefault|DeclareOldFontCommand|DeclareFontShape|DeclareMathVersion|DeclarePairedDelimiter|"
    rb"DeclarePairedDelimiterX|NewCommandCopy|newsiamthm|newsiamremark)\*?\s*\{?\s*\\([A-Za-z@]+)")
DEF_ENV = re.compile(
    rb"\\(?:newenvironment|renewenvironment|provideenvironment|NewDocumentEnvironment|DeclareDocumentEnvironment|"
    rb"RenewDocumentEnvironment|newtheorem|newaliascnt|newcounter|NewEnviron|newtcolorbox|newmdenv)\*?\s*\{([A-Za-z@*]+)\}")
KERNEL_FILES = re.compile(r"^(latex\.ltx|ltx.*|fontdef\.ltx|.*\.ltx)$")
REQUIRE_RE = re.compile(rb"\\(?:RequirePackage|usepackage|LoadClass|LoadClassWithOptions|RequirePackageWithOptions)"
                        rb"\s*(?:\[[^\]]*\])?\s*\{([^}]*)\}|\\input\s*\{?([A-Za-z0-9_.\-]+)"
                        rb"|\\use(tikz|pgf)library\s*(?:\[[^\]]*\])?\s*\{([^}]*)\}")
INDEX_VERSION = 3


def _scan(data, cs, env, tag):
    for m in DEF_CS.finditer(data):
        name = (m.group(1) or m.group(2)).decode("latin-1")
        cs.setdefault(name, set()).add(tag)
        if name.startswith("end") and len(name) > 3:
            # `\def\foo` + `\def\endfoo` is how plain-style code defines environment foo
            env.setdefault(name[3:], set()).add(tag)
    for m in DEF_ENV.finditer(data):
        name = m.group(1).decode("latin-1")
        env.setdefault(name, set()).add(tag)


def _requires(data):
    out = set()
    for m in REQUIRE_RE.finditer(data):
        if m.group(1):
            out.update(n.strip().decode("latin-1") for n in m.group(1).split(b",") if n.strip())
        elif m.group(2):
            out.add(os.path.splitext(m.group(2).decode("latin-1"))[0])
        elif m.group(3):
            # \usetikzlibrary{cd} loads tikzlibrarycd.code.tex
            out.update(f"{m.group(3).decode()}library{n.strip().decode('latin-1')}.code"
                       for n in m.group(4).split(b",") if n.strip())
    return out


def texlive_index(texmf, cache):
    """{"cs": {name: [file, ...]}, "env": {...}} over the TeX Live tree."""
    stamp_file = os.path.join(texmf, "ls-R")
    stamp = os.path.getmtime(stamp_file) if os.path.isfile(stamp_file) else 0
    path = os.path.join(cache, f"definers-v{INDEX_VERSION}.json")
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            j = json.load(f)
        if j.get("texmf") == texmf and j.get("stamp") == stamp:
            return j
    cs, env, req = {}, {}, {}
    for sub in ("tex/latex", "tex/generic"):
        root = os.path.join(texmf, sub)
        for dirpath, dirnames, files in os.walk(root):
            dirnames.sort()
            for f in files:
                if not f.endswith((".sty", ".cls", ".ltx", ".def", ".clo", ".tex")):
                    continue
                try:
                    with open(os.path.join(dirpath, f), "rb") as fh:
                        data = fh.read()
                except OSError:
                    continue
                _scan(data, cs, env, f)
                r = _requires(data)
                if r:
                    req.setdefault(os.path.splitext(f)[0], set()).update(r)
    j = {"texmf": texmf, "stamp": stamp, "cs": {k: sorted(v) for k, v in cs.items()},
         "env": {k: sorted(v) for k, v in env.items()}, "requires": {k: sorted(v) for k, v in req.items()}}
    os.makedirs(cache, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(j, f)
    return j


LOAD_RE = re.compile(r"\\(documentclass|usepackage|RequirePackage|LoadClass|usetikzlibrary|usepgflibrary)"
                     r"\s*(?:\[[^\]]*\])?\s*\{([^}]*)\}")


def project_facts(root):
    """What the project itself loads and defines: {"class", "packages",
    "cs_tex", "cs_sty", "env_tex", "env_sty"} (names, no backslash)."""
    facts = {"class": None, "packages": [], "cs_tex": set(), "cs_sty": set(), "env_tex": set(), "env_sty": set()}
    for dirpath, _, files in os.walk(root):
        for f in files:
            if not f.endswith((".tex", ".sty", ".cls", ".ltx", ".def", ".clo")):
                continue
            try:
                with open(os.path.join(dirpath, f), "rb") as fh:
                    data = fh.read()
            except OSError:
                continue
            kind = "tex" if f.endswith(".tex") else "sty"
            cs, env = {}, {}
            _scan(data, cs, env, f)
            facts["cs_" + kind].update(cs)
            facts["env_" + kind].update(env)
            if kind == "tex":
                text = data.decode("latin-1")
                text = "\n".join(line.split("%", 1)[0] for line in text.splitlines())
                for m in LOAD_RE.finditer(text):
                    names = [n.strip() for n in m.group(2).split(",") if n.strip()]
                    if m.group(1) == "documentclass" and names and not facts["class"]:
                        facts["class"] = names[0]
                    elif m.group(1) in ("usetikzlibrary", "usepgflibrary"):
                        facts["packages"].extend(f"{m.group(1)[3:-7]}library{n}.code" for n in names)
                    elif m.group(1) != "documentclass":
                        facts["packages"].extend(names)
    facts["packages"] = sorted(set(facts["packages"]))
    return {k: (sorted(v) if isinstance(v, set) else v) for k, v in facts.items()}


def _label(fname):
    base, ext = os.path.splitext(fname)
    if KERNEL_FILES.match(fname) or fname in ("fontdef.ltx",):
        return "LaTeX kernel"
    if ext == ".cls":
        return f"class {base}"
    if ext == ".clo":
        return f"class options {base}"
    if ext == ".def":
        return f"package {base} (.def)"
    return f"package {base}"


def closure(facts, index, depth=4):
    """Packages/classes the document loads, directly or through
    `\\RequirePackage`/`\\LoadClass`/`\\input`/`\\usetikzlibrary` chains
    (depth-bounded): {name: (load depth, the directly loaded package or
    class it was reached through)}, depth 0 = loaded by the document."""
    req = (index or {}).get("requires", {})
    order = {}
    cls = facts.get("class")
    frontier = ([(cls, cls)] if cls else []) + [(p, p) for p in facts.get("packages") or ()]
    for d in range(depth + 1):
        nxt = []
        for n, root in frontier:
            if n in order:
                continue
            order[n] = (d, root)
            nxt.extend((c, root) for c in req.get(n, ()))
        frontier = nxt
    return order


def definer(kind, name, facts, index, loaded=None):
    """Group label for construct `name` (kind "cs" or "env") in a document
    with `facts` (from project_facts); None when no definer is found in the
    project, the document's load closure or the kernel."""
    if kind == "cs":
        name = name.lstrip("\\").rstrip("*")
    if name in facts.get(f"{kind}_sty", ()):
        return "project .sty/.cls (not read)"
    if name in facts.get(f"{kind}_tex", ()):
        return "project macro (defined in the document)"
    files = (index or {}).get(kind, {}).get(name)
    if not files:
        return None
    if loaded is None:
        loaded = closure(facts, index)
    hits = [f for f in files if os.path.splitext(f)[0] in loaded]
    if hits:
        # shallowest load first; a LaTeX package over a plain .tex input; a
        # package the document loads over its class (a class drags in
        # option-conditional alternatives such as amstex)
        cls = facts.get("class")

        def key(f):
            d, root = loaded[os.path.splitext(f)[0]]
            return (d, f.endswith(".tex"), root == cls and d > 0, f)
        best = min(hits, key=key)
        d, root = loaded[os.path.splitext(best)[0]]
        # grouped by what the document itself loads: that is what a lane implements
        return ("class " if root == cls else "package ") + root
    for f in files:
        if KERNEL_FILES.match(f):
            return "LaTeX kernel"
    return None


KEY_RE = re.compile(r"^[^:]+: (cs|env) (\S+)$")


def group_of(key, facts, index, loaded=None):
    """Group label for a blocker key; the key itself when it names no
    construct or none is found."""
    m = KEY_RE.match(key)
    if m:
        label = definer(m.group(1), m.group(2), facts, index, loaded)
        if label:
            return label
    m = re.match(r"^[^:]+: package (\S+)$", key)
    if m:
        return f"package {m.group(1)}"
    return key
