"""Who defines a construct FlashTeX did not know? (root-cause grouping)

Oracle tooling only (standard library). A diagnostic names a construct
(`\\texorpdfstring`, `\\subjclass`, environment `alignat`); the construct
itself is rarely the root cause -- the package or class that defines it is,
and one package usually brings a dozen of them. This module answers "who
defines it" from the *sources*, never from FlashTeX:

1. the document's own files (a `\\newcommand`/`\\def` in the project's .tex,
   or a project-local .sty/.cls) -> `project: .tex` / `project: .sty/.cls`;
2. the TeX Live tree (`tex/latex`, `tex/generic`), indexed once by a regex
   over every `.sty`/`.cls`/`.ltx`/`.def` for definitions (`\\def`,
   `\\newcommand`, `\\DeclareRobustCommand`, `\\DeclareMathSymbol`,
   `\\newenvironment`, `\\newtheorem`, ...) -> `class X` / `package X` /
   `LaTeX kernel`, preferring a definer the document actually loads.

The index is cached in the parity cache keyed by the tree's path and the
modification time of its `ls-R` database. It is a heuristic: a construct
generated by `\\csname` or defined in a `.dtx`-only file is not found and
keeps its own key.
"""

import json
import os
import re

DEF_CS = re.compile(
    rb"\\(?:def|gdef|edef|xdef|let|global\\def|global\\let|global\\edef|chardef|mathchardef|countdef|dimendef|"
    rb"skipdef|toksdef|newcount|newdimen|newskip|newtoks|newbox|newif)\s*\\([A-Za-z@]+)"
    rb"|\\(?:newcommand|renewcommand|providecommand|DeclareRobustCommand|DeclareMathOperator|NewDocumentCommand|"
    rb"DeclareDocumentCommand|ProvideDocumentCommand|RenewDocumentCommand|newrobustcmd|renewrobustcmd|"
    rb"providerobustcmd|DeclareMathSymbol|DeclareMathAlphabet|DeclareMathDelimiter|DeclareMathAccent|"
    rb"DeclareMathRadical|DeclareTextCommand|DeclareTextSymbol|DeclareTextAccent|DeclareTextCommandDefault|"
    rb"DeclareTextSymbolDefault|DeclareOldFontCommand|DeclareFontShape|DeclareMathVersion|DeclarePairedDelimiter|"
    rb"DeclarePairedDelimiterX|NewCommandCopy|newsiamthm|newsiamremark|DeclareTextFontCommand|DeclareFixedFont|"
    rb"DeclareSymbolFontAlphabet|newlength)\*?\s*\{?\s*\\([A-Za-z@]+)")
# `\let\author\relax` (\maketitle's cleanup) and `\let\x\@undefined` undefine, they do not define
UNDEFINE_TAIL = re.compile(rb"\s*=?\s*\\(relax|@empty|@undefined|undefined|@gobble)(?![A-Za-z@])")
DEF_ENV = re.compile(
    rb"\\(?:newenvironment|renewenvironment|provideenvironment|NewDocumentEnvironment|DeclareDocumentEnvironment|"
    rb"RenewDocumentEnvironment|newtheorem|newaliascnt|newcounter|NewEnviron|newtcolorbox|newmdenv)\*?\s*\{([A-Za-z@*]+)\}")
# The kernel's own files (`latex.ltx`, `fontmath.ltx`, `latex-lab-*.ltx`, ...);
# *not* `ltx*.sty` (revtex's ltxfront/ltxutil, ltxtools) nor `mylatexformat`.
KERNEL_FILES = re.compile(r"^(?!mylatexformat)[A-Za-z0-9-]+\.ltx$")
REQUIRE_RE = re.compile(rb"\\(?:RequirePackage|usepackage|LoadClass|LoadClassWithOptions|RequirePackageWithOptions)"
                        rb"\s*(?:\[[^\]]*\])?\s*\{([^}]*)\}|\\input\s*\{?([A-Za-z0-9_.\-]+)"
                        rb"|\\use(tikz|pgf)library\s*(?:\[[^\]]*\])?\s*\{([^}]*)\}")
REG_DEF = re.compile(rb"\\(?:newcount|newdimen|newskip|newmuskip|newtoks|newbox|newlength|countdef|dimendef|skipdef|"
                     rb"toksdef|chardef|mathchardef)\s*\{?\s*\\([A-Za-z@]+)")
INDEX_VERSION = 6

# TeX82 + e-TeX + pdfTeX primitives a document is likely to use directly. A
# construct here is not "defined" by any file; it is engine vocabulary.
# (`\end` is left out: LaTeX redefines it, and its errors are environment errors.)
PRIMITIVES = set("""
above abovedisplayshortskip abovedisplayskip abovewithdelims accent adjdemerits advance afterassignment aftergroup
atop atopwithdelims badness baselineskip batchmode begingroup belowdisplayshortskip belowdisplayskip binoppenalty
botmark box boxmaxdepth brokenpenalty catcode char chardef cleaders closein closeout clubpenalty copy count countdef
cr crcr csname day deadcycles def defaulthyphenchar defaultskewchar delcode delimiter delimiterfactor delimitershortfall
dimen dimendef discretionary displayindent displaylimits displaystyle displaywidowpenalty displaywidth divide
doublehyphendemerits dp dump edef else emergencystretch endcsname endgroup endinput endlinechar eqno errhelp
errmessage errorcontextlines errorstopmode escapechar everycr everydisplay everyhbox everyjob everymath everypar
everyvbox exhyphenpenalty expandafter fam fi finalhyphendemerits firstmark floatingpenalty font fontdimen fontname
futurelet gdef global globaldefs halign hangafter hangindent hbadness hbox hfil hfill hfilneg hfuzz hoffset holdinginserts
hrule hsize hskip hss ht hyphenation hyphenchar hyphenpenalty if ifcase ifcat ifdim ifeof iffalse ifhbox ifhmode ifinner
ifmmode ifnum ifodd iftrue ifvbox ifvmode ifvoid ifx ignorespaces immediate indent input inputlineno insert insertpenalties
interlinepenalty jobname kern language lastbox lastkern lastpenalty lastskip lccode leaders left lefthyphenmin leftskip leqno
let limits linepenalty lineskip lineskiplimit long looseness lower lowercase mag mark mathaccent mathbin mathchar
mathchardef mathchoice mathclose mathcode mathinner mathop mathopen mathord mathpunct mathrel mathsurround maxdeadcycles
maxdepth meaning medmuskip message middle mkern month moveleft moveright mskip multiply muskip muskipdef newlinechar noalign
noboundary noexpand noindent nolimits nonscript nonstopmode nulldelimiterspace nullfont number omit openin openout or outer
output outputpenalty over overfullrule overline overwithdelims pagedepth pagefilllstretch pagefillstretch pagefilstretch
pagegoal pageshrink pagestretch pagetotal par parfillskip parindent parshape parskip patterns pausing penalty
postdisplaypenalty predisplaypenalty predisplaysize pretolerance prevdepth prevgraf radical raise read relax relpenalty
right righthyphenmin rightskip romannumeral scriptfont scriptscriptfont scriptscriptstyle scriptspace scriptstyle
scrollmode setbox setlanguage sfcode shipout show showbox showboxbreadth showboxdepth showlists showthe skewchar skip
skipdef spacefactor spaceskip span special splitbotmark splitfirstmark splitmaxdepth splittopskip string tabskip textfont
textstyle the thickmuskip thinmuskip time toks toksdef tolerance topmark topskip tracingcommands tracinglostchars
tracingmacros tracingonline tracingoutput tracingpages tracingparagraphs tracingrestores tracingstats uccode uchyph
underline unhbox unhcopy unkern unpenalty unskip unvbox unvcopy uppercase vadjust valign vbadness vbox vcenter vfil vfill
vfilneg vfuzz voffset vrule vsize vskip vsplit vss vtop wd widowpenalty write xdef xleaders xspaceskip year
detokenize dimexpr glueexpr numexpr muexpr protected unexpanded ifdefined ifcsname unless scantokens eTeXversion
lastlinefit interactionmode showtokens readline pdfstrcmp pdfoutput pdfpagewidth pdfpageheight pdfminorversion
pdfcompresslevel pdfobjcompresslevel pdfinfo pdfcatalog pdfsavepos pdflastxpos pdflastypos pdfliteral pdfximage
pdfrefximage pdfsetmatrix pdfstartlink pdfendlink pdfdest pdfoutline pdfadjustspacing pdfprotrudechars pdfglyphtounicode
pdfgentounicode pdfsuppresswarningpagegroup pdfpkresolution pdfmapfile pdfmapline
""".split())


def _scan(data, cs, env, tag, reg=None):
    for m in DEF_CS.finditer(data):
        if m.group(1) and b"let" in m.group(0)[:12] and UNDEFINE_TAIL.match(data, m.end()):
            continue
        name = (m.group(1) or m.group(2)).decode("latin-1")
        cs.setdefault(name, set()).add(tag)
        if name.startswith("end") and len(name) > 3:
            # `\def\foo` + `\def\endfoo` is how plain-style code defines environment foo
            env.setdefault(name[3:], set()).add(tag)
    for m in DEF_ENV.finditer(data):
        name = m.group(1).decode("latin-1")
        env.setdefault(name, set()).add(tag)
    if reg is not None:
        for m in REG_DEF.finditer(data):
            reg.add(m.group(1).decode("latin-1"))


def _requires(data):
    out = set()
    for m in REQUIRE_RE.finditer(data):
        if m.group(1):
            out.update(n.strip().decode("latin-1") for n in m.group(1).split(b",") if n.strip())
        elif m.group(2):
            out.add(os.path.splitext(m.group(2).decode("latin-1"))[0])
        elif m.group(3):
            # \usetikzlibrary{cd} loads tikzlibrarycd.code.tex
            out.update(f"{m.group(3).decode()}library{n.strip().decode('latin-1')}.code"
                       for n in m.group(4).split(b",") if n.strip())
    return out


def texlive_index(texmf, cache):
    """{"cs": {name: [file, ...]}, "env": {...}} over the TeX Live tree."""
    stamp_file = os.path.join(texmf, "ls-R")
    stamp = os.path.getmtime(stamp_file) if os.path.isfile(stamp_file) else 0
    path = os.path.join(cache, f"definers-v{INDEX_VERSION}.json")
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            j = json.load(f)
        if j.get("texmf") == texmf and j.get("stamp") == stamp:
            return j
    cs, env, req, kreg = {}, {}, {}, set()
    for sub in ("tex/latex", "tex/generic"):
        root = os.path.join(texmf, sub)
        for dirpath, dirnames, files in os.walk(root):
            dirnames.sort()
            for f in files:
                if not f.endswith((".sty", ".cls", ".ltx", ".def", ".clo", ".tex")):
                    continue
                try:
                    with open(os.path.join(dirpath, f), "rb") as fh:
                        data = fh.read()
                except OSError:
                    continue
                _scan(data, cs, env, f, kreg if KERNEL_FILES.match(f) else None)
                r = _requires(data)
                if r:
                    req.setdefault(os.path.splitext(f)[0], set()).update(r)
    j = {"texmf": texmf, "stamp": stamp, "cs": {k: sorted(v) for k, v in cs.items()},
         "env": {k: sorted(v) for k, v in env.items()}, "requires": {k: sorted(v) for k, v in req.items()},
         "kernel_registers": sorted(kreg)}
    os.makedirs(cache, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(j, f)
    return j


LOAD_RE = re.compile(r"\\(documentclass|usepackage|RequirePackage|LoadClass|usetikzlibrary|usepgflibrary)"
                     r"\s*(?:\[[^\]]*\])?\s*\{([^}]*)\}")


def project_facts(root):
    """What the project itself loads and defines: {"class", "packages",
    "cs_tex", "cs_sty", "env_tex", "env_sty"} (names, no backslash)."""
    facts = {"class": None, "packages": [], "cs_tex": set(), "cs_sty": set(), "env_tex": set(), "env_sty": set(),
             "local_files": set()}
    for dirpath, _, files in os.walk(root):
        for f in files:
            if not f.endswith((".tex", ".sty", ".cls", ".ltx", ".def", ".clo")):
                continue
            try:
                with open(os.path.join(dirpath, f), "rb") as fh:
                    data = fh.read()
            except OSError:
                continue
            kind = "tex" if f.endswith(".tex") else "sty"
            if kind == "sty":
                facts["local_files"].add(f)
            cs, env = {}, {}
            _scan(data, cs, env, f)
            facts["cs_" + kind].update(cs)
            facts["env_" + kind].update(env)
            if kind == "tex":
                text = data.decode("latin-1")
                text = "\n".join(line.split("%", 1)[0] for line in text.splitlines())
                for m in LOAD_RE.finditer(text):
                    names = [n.strip() for n in m.group(2).split(",") if n.strip()]
                    if m.group(1) == "documentclass" and names and not facts["class"]:
                        facts["class"] = names[0]
                    elif m.group(1) in ("usetikzlibrary", "usepgflibrary"):
                        facts["packages"].extend(f"{m.group(1)[3:-7]}library{n}.code" for n in names)
                    elif m.group(1) != "documentclass":
                        facts["packages"].extend(names)
    facts["packages"] = sorted(set(facts["packages"]))
    return {k: (sorted(v) if isinstance(v, set) else v) for k, v in facts.items()}


def _label(fname):
    base, ext = os.path.splitext(fname)
    if KERNEL_FILES.match(fname) or fname in ("fontdef.ltx",):
        return "LaTeX kernel"
    if ext == ".cls":
        return f"class {base}"
    if ext == ".clo":
        return f"class options {base}"
    if ext == ".def":
        return f"package {base} (.def)"
    return f"package {base}"


def closure(facts, index, depth=4):
    """Packages/classes the document loads, directly or through
    `\\RequirePackage`/`\\LoadClass`/`\\input`/`\\usetikzlibrary` chains
    (depth-bounded): {name: (load depth, the directly loaded package or
    class it was reached through)}, depth 0 = loaded by the document."""
    req = (index or {}).get("requires", {})
    order = {}
    cls = facts.get("class")
    frontier = ([(cls, cls)] if cls else []) + [(p, p) for p in facts.get("packages") or ()]
    for d in range(depth + 1):
        nxt = []
        for n, root in frontier:
            if n in order:
                continue
            order[n] = (d, root)
            nxt.extend((c, root) for c in req.get(n, ()))
        frontier = nxt
    return order


def definer(kind, name, facts, index, loaded=None):
    """Group label for construct `name` (kind "cs" or "env") in a document
    with `facts` (from project_facts); None when nothing is found.

    Precedence, first match wins:
      1. a TeX primitive (`\\vskip`, `\\kern`, `\\baselineskip`) -> one group;
      2. a project-local .sty/.cls that defines it (FlashTeX does not read it);
      3. the document class or a file the class loads (a class *redefines*
         kernel commands: amsart's `\\author`, `\\email`);
      4. a LaTeX kernel register (`\\textwidth`, `\\topsep`) -> one group;
      5. a LaTeX kernel command -> `LaTeX kernel: \\name`, one key per command
         (the kernel is too big to be one lane);
      6. a macro the document defines itself;
      7. the package the document loads whose closure reaches a definer
         shallowest (packages *patch* kernel commands, so they come after it).
    """
    if kind == "cs":
        name = name.lstrip("\\").rstrip("*")
        if name in PRIMITIVES:
            return "TeX primitive"
    if name in facts.get(f"{kind}_sty", ()):
        return "project .sty/.cls (read, incompletely)"
    files = (index or {}).get(kind, {}).get(name) or []
    if loaded is None:
        loaded = closure(facts, index)
    cls = facts.get("class")
    hits = [f for f in files if os.path.splitext(f)[0] in loaded]

    def key(f):
        # shallowest load first; a LaTeX file over a plain .tex input; below
        # the class itself, a package the document loads over one the class
        # drags in (amsart loads amstex for an option the document never sets)
        d, root = loaded[os.path.splitext(f)[0]]
        return (d, f.endswith(".tex"), root == cls and d > 0, f)
    best_root = loaded[os.path.splitext(min(hits, key=key))[0]][1] if hits else None
    if cls and best_root == cls:
        return f"class {cls}"
    if kind == "cs":
        if index is not None and "_kreg" not in index:
            index["_kreg"] = set(index.get("kernel_registers", ()))
        if name in (index or {}).get("_kreg", ()):
            return "LaTeX kernel register (length/skip/count)"
    if any(KERNEL_FILES.match(f) for f in files):
        return "LaTeX kernel: " + ("\\" + name if kind == "cs" else f"environment {name}")
    if name in facts.get(f"{kind}_tex", ()):
        return "project macro (defined in the document)"
    if hits:
        # grouped by what the document itself loads: that is what a lane implements
        return "package " + best_root
    return None


KEY_RE = re.compile(r"^[^:]+: (cs|env) (\S+)(?: \(([^)]*)\))?(?: <- (\S+))?$")
VIA_RE = re.compile(r" <- (\S+)$")


def group_of(key, facts, index, loaded=None):
    """Group label for a blocker key (see `parity.diag_causes` for its
    shape); the key itself when it names nothing groupable.

    A key that fired while FlashTeX was reading a `.sty`/`.cls` (`<- file`)
    belongs to that file: `project .sty/.cls (read, incompletely)` when the
    file is the project's own, else its package/class. Otherwise the named
    construct's definer (`definer`); a kernel command keeps its context
    (`LaTeX kernel: \\hspace (in math mode)` is a different fix from an
    unknown `\\hspace`)."""
    m = KEY_RE.match(key)
    via = VIA_RE.search(key)
    if via:
        f = via.group(1)
        local = set(facts.get("local_files") or ())
        if f in local or re.sub(r"<N>", "", f) in {re.sub(r"\d+", "", x) for x in local}:
            return "project .sty/.cls (read, incompletely)"
        base, ext = os.path.splitext(f)
        return ("class " if ext == ".cls" else "package ") + base
    if m:
        label = definer(m.group(1), m.group(2), facts, index, loaded)
        if label:
            if label.startswith("LaTeX kernel: ") and m.group(3):
                label += f" ({m.group(3)})"
            return label
    m = re.match(r"^[^:]+: package (\S+)$", key)
    if m:
        return f"package {m.group(1)}"
    return key
